//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:15:00 PM BST 
//


package uk.ac.ebi.biosamples.xml.resultquery;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import uk.ac.ebi.biosamples.xml.summaryinfo.SummaryInfo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ebi.ac.uk/biosamples/SummaryInfo}SummaryInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "summaryInfo"
})
@XmlRootElement(name = "ResultQuery")
public class ResultQuery {

    @XmlElement(name = "SummaryInfo", namespace = "http://www.ebi.ac.uk/biosamples/SummaryInfo", required = true)
    protected SummaryInfo summaryInfo;

    /**
     * Gets the value of the summaryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SummaryInfo }
     *     
     */
    public SummaryInfo getSummaryInfo() {
        return summaryInfo;
    }

    /**
     * Sets the value of the summaryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SummaryInfo }
     *     
     */
    public void setSummaryInfo(SummaryInfo value) {
        this.summaryInfo = value;
    }

}
