image: docker:stable
services:
  - docker:stable-dind

variables:
  DEPLOY_PATH: ~/gitlab

before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - apk update && apk add git

stages:
  - package
  - config
  - deploy

maven-package:
  image: eclipse-temurin:17-jdk
  stage: package
  script:
    - './mvnw -q deploy -P embl-ebi -s ci_settings.xml -DskipTests -Dmaven.source.skip=true'
    - mkdir deployment
    - cp webapps/core/target/webapps-core-*.war deployment/webapps-core.war
    - cp webapps/core-v2/target/webapps-core-v2*.jar deployment/webapps-core-v2.jar
    - cp agents/solr/target/agents-solr-*.jar deployment/agents-solr.jar
    - cp agents/uploadworkers/target/agents-uploadworkers-*.jar deployment/agents-uploadworkers.jar
    - cp pipelines/curation/target/pipelines-curation-*.jar deployment/pipelines-curation.jar
    # - cp pipelines/ena/target/pipelines-ena-*.jar deployment/pipelines-ena.jar
    # - cp pipelines/ncbi-ena-link/target/pipelines-ncbi-ena-link-*.jar deployment/pipelines-ncbi-ena-link.jar
    - cp pipelines/sample-release/target/pipelines-sample-release-*.jar deployment/pipelines-sample-release.jar
    - cp pipelines/sample-post-release-action/target/pipelines-sample-post-release-action*.jar deployment/pipelines-sample-post-release-action.jar
    - cp pipelines/ncbi/target/pipelines-ncbi-*.jar deployment/pipelines-ncbi.jar
    - cp pipelines/reindex/target/pipelines-reindex-*.jar deployment/pipelines-reindex.jar
    - cp pipelines/sample-transformation-dtol/target/pipelines-sample-transformation-dtol-*.jar deployment/pipelines-sample-transformation-dtol.jar
  artifacts:
    paths:
      - deployment
#  when: manual

clone-config-preproduction:
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/biosamples-internal.git
    - mkdir config
    - cp -r biosamples-internal/script/* deployment/
    - cp -r biosamples-internal/wwwdev/* config/
    - cp biosamples-internal/deployment/deploy.sh ./
  artifacts:
    paths:
      - deployment
      - config
      - deploy.sh
  when: manual

clone-config-production:
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/biosamples-internal.git
    - mkdir config
    - cp -r biosamples-internal/script/* deployment/
    - cp -r biosamples-internal/www/* config/
    - cp biosamples-internal/deployment/deploy.sh ./
    - cp biosamples-internal/deployment/deploy_agents_solr.sh ./
  artifacts:
    paths:
      - deployment
      - config
      - deploy.sh
      - deploy_agents_solr.sh
  when: manual
  only:
    - master

deploy-preproduction:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/ubuntu:latest
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh bsd_dev wp-np2-40
  when: manual
  only:
    - refactoring_1_2024
    - dev
    - master

deploy-production-p2m-servers:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/ubuntu:latest
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh bsd_prod wp-p2m-40
    - ./deploy.sh bsd_prod wp-p2m-41
    - ./deploy_agents_solr.sh bsd_prod wp-p2m-42
  when: manual
  only:
    - master

deploy-production-p1m-servers:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/ubuntu:latest
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh bsd_prod wp-p1m-40
    - ./deploy.sh bsd_prod wp-p1m-41
    - ./deploy_agents_solr.sh bsd_prod wp-p1m-42
  when: manual
  only:
    - master
