image: docker:latest

stages:
  - config
  - deploy


clone-config:
  image: maven:3.6-jdk-11
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk:biosamples/biosamples-internal.git
    - cd ./biosamples-internal && ls
  only:
    - BSD-2130-package-BSD-in-GL

deploy:
  image: ubuntu
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 "rm -rf ~/gitlab/*"
    - scp -r -v -o StrictHostKeyChecking=no ./target/*.jar tc_spo01@wp-np2-40:~/gitlab/bsd/json-schema-store.jar
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 "~/gitlab/start.sh"
  only:
    - BSD-2130-package-BSD-in-GL