image: docker:latest

variables:
  DEPLOY_PATH: ~/gitlab

before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR

stages:
  - package
  - config
  - deploy

maven-package:
  image: maven:3.6-jdk-11
  stage: package
  script:
    - 'mvn -e deploy -P embl-ebi -s ci_settings.xml -Dmaven.source.skip=true'
    - mkdir deployment
    - cp webapps/core/target/webapps-core-*.war deployment/webapps-core.war
    - cp agents/solr/target/agents-solr-*.jar deployment/agents-solr.jar
    - cp agents/uploadworkers/target/agents-uploadworkers-*.jar deployment/agents-uploadworkers.jar
    - cp pipelines/clearinghouse/target/pipelines-clearinghouse-*.jar deployment/pipelines-clearinghouse.jar
    - cp pipelines/copydown/target/pipelines-copydown-*.jar deployment/pipelines-copydown.jar
    - cp pipelines/curami/target/pipelines-curami-*.jar deployment/pipelines-curami.jar
    - cp pipelines/curatedview/target/pipelines-curated-view-*.jar deployment/pipelines-curated-view.jar
    - cp pipelines/curation/target/pipelines-curation-*.jar deployment/pipelines-curation.jar
    - cp pipelines/curationundo/target/pipelines-curation-undo-*.jar deployment/pipelines-curation-undo.jar
    - cp pipelines/ebeye-search-export/target/pipelines-ebeye-search-export-*.jar deployment/pipelines-ebeye-search-export.jar
    - cp pipelines/ena/target/pipelines-ena-*.jar deployment/pipelines-ena.jar
    - cp pipelines/ena-amr/target/pipelines-ena-amr-*.jar deployment/pipelines-ena-amr.jar
    - cp pipelines/export/target/pipelines-export-*.jar deployment/pipelines-export.jar
    - cp pipelines/livelist/target/pipelines-livelist-*.jar deployment/pipelines-livelist.jar
    - cp pipelines/ncbi/target/pipelines-ncbi-*.jar deployment/pipelines-ncbi.jar
    - cp pipelines/neoexport/target/pipelines-neoexport-*.jar deployment/pipelines-neoexport.jar
    - cp pipelines/reindex/target/pipelines-reindex-*.jar deployment/pipelines-reindex.jar
    - cp pipelines/zooma/target/pipelines-zooma-*.jar deployment/pipelines-zooma.jar
  artifacts:
    paths:
      - deployment
  when: manual

clone-config-preproduction:
  image: maven:3.6-jdk-11
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/biosamples-internal.git
    - mkdir config
    - cp -r biosamples-internal/script/* deployment/
    - cp -r biosamples-internal/wwwdev/* config/
  artifacts:
    paths:
      - deployment
      - config
  when: manual

clone-config-production:
  image: maven:3.6-jdk-11
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/biosamples-internal.git
    - mkdir config
    - cp -r biosamples-internal/script/* deployment/
    - cp -r biosamples-internal/www/* config/
  artifacts:
    paths:
      - deployment
      - config
  when: manual
  only:
    - master

deploy-preproduction:
  image: ubuntu
  stage: deploy
  script:
    - ls deployment/
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # stop running services
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 '/mnt/data/biosamples/servers/monit/wp-np2-40.2812/monit.sh stop agents-solr'
    - sleep 60
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 '/mnt/data/biosamples/servers/monit/wp-np2-40.2812/monit.sh stop webapps-core'
    - sleep 60
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 '/mnt/data/biosamples/servers/monit/wp-np2-40.2812/stop.sh'
    - sleep 60
    # remove old artifacts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'rm -rf /mnt/data/biosamples/sw/wwwdev/*.jar'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'rm -rf /mnt/data/biosamples/sw/wwwdev/*.war'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'rm -rf /mnt/data/biosamples/sw/wwwdev/*.sh'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'rm -rf /mnt/data/biosamples/sw/wwwdev/*.js'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'rm -rf /mnt/data/biosamples/sw/wwwdev/*.py'
    # Copy scripts and other config
    - scp -r -v -o StrictHostKeyChecking=no deployment/* tc_spo01@wp-np2-40:/mnt/data/biosamples/sw/wwwdev/
    - scp -r -v -o StrictHostKeyChecking=no config/* tc_spo01@wp-np2-40:/mnt/data/biosamples/
    # mark all scripts as executable
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'chmod ug+x /mnt/data/biosamples/sw/wwwdev/*.sh'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'chmod ug+x /mnt/data/biosamples/servers/*/*/*.sh'
    # monit config
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'chmod 0700 /mnt/data/biosamples/servers/monit/*/monit.conf'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'mkdir -p /mnt/data/biosamples/logs/monit/wp-np2-40.2812'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'mkdir -p /mnt/data/biosamples/data/monit/wp-np2-40.2812'
    # install cron script
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 'crontab /mnt/data/biosamples/servers/crontab.wp-np2-40.conf'
    # start up and monitor everything
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 '/mnt/data/biosamples/servers/monit/wp-np2-40.2812/start.sh'
    - sleep 15
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 '/mnt/data/biosamples/servers/monit/wp-np2-40.2812/monit.sh start all'
    # poll for services
    - sleep 3000
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-np2-40 /mnt/data/biosamples/sw/wwwdev/http-status-check -t 3600 -u 'http://wp-np2-40.ebi.ac.uk:8081/biosamples/health'
  when: manual
  only:
    - dev
    - master

deploy-production-p2m-servers:
  image: ubuntu
  stage: deploy
  script:
    - ls deployment/
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # deploy to wp-p2m-40
    # stop running services
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 '/mnt/data/biosamples/servers/monit/wp-p2m-40.2812/monit.sh stop agents-solr'
    - sleep 60
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 '/mnt/data/biosamples/servers/monit/wp-p2m-40.2812/monit.sh stop webapps-core'
    - sleep 60
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 '/mnt/data/biosamples/servers/monit/wp-p2m-40.2812/stop.sh'
    - sleep 60
    # remove old artifacts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'rm -rf /mnt/data/biosamples/sw/www/*.jar'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'rm -rf /mnt/data/biosamples/sw/www/*.war'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'rm -rf /mnt/data/biosamples/sw/www/*.sh'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'rm -rf /mnt/data/biosamples/sw/www/*.js'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'rm -rf /mnt/data/biosamples/sw/www/*.py'
    # Copy scripts and other config
    - scp -r -v -o StrictHostKeyChecking=no deployment/* tc_spo01@wp-p2m-40:/mnt/data/biosamples/sw/www/
    - scp -r -v -o StrictHostKeyChecking=no config/* tc_spo01@wp-p2m-40:/mnt/data/biosamples/
    - scp -r -v -o StrictHostKeyChecking=no /mnt/data/biosamples/sw/www/wp-p2m-40/ tc_spo01@wp-p2m-40:/mnt/data/biosamples/sw/www/
    # mark all scripts as executable
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'chmod ug+x /mnt/data/biosamples/sw/www/*.sh'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'chmod ug+x /mnt/data/biosamples/servers/*/*/*.sh'
    # monit config
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'chmod 0700 /mnt/data/biosamples/servers/monit/*/monit.conf'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'mkdir -p /mnt/data/biosamples/logs/monit/wp-p2m-40.2812'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'mkdir -p /mnt/data/biosamples/data/monit/wp-p2m-40.2812'
    # install cron script
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 'crontab /mnt/data/biosamples/servers/crontab.wp-p2m-40.conf'
    # start up and monitor everything
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 '/mnt/data/biosamples/servers/monit/wp-p2m-40.2812/start.sh'
    - sleep 15
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 '/mnt/data/biosamples/servers/monit/wp-p2m-40.2812/monit.sh start all'
    # poll for services
    - sleep 300
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-40 /mnt/data/biosamples/sw/www/http-status-check -t 3600 -u 'http://wp-p2m-40.ebi.ac.uk:8081/biosamples/health'
    # deploy to wp-p2m-41
    # stop running services
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 '/mnt/data/biosamples/servers/monit/wp-p2m-41.2812/monit.sh stop agents-solr'
    - sleep 60
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 '/mnt/data/biosamples/servers/monit/wp-p2m-41.2812/monit.sh stop webapps-core'
    - sleep 60
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 '/mnt/data/biosamples/servers/monit/wp-p2m-41.2812/stop.sh'
    - sleep 60
    # remove old artifacts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'rm -rf /mnt/data/biosamples/sw/www/*.jar'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'rm -rf /mnt/data/biosamples/sw/www/*.war'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'rm -rf /mnt/data/biosamples/sw/www/*.sh'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'rm -rf /mnt/data/biosamples/sw/www/*.js'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'rm -rf /mnt/data/biosamples/sw/www/*.py'
    # Copy scripts and other config
    - scp -r -v -o StrictHostKeyChecking=no deployment/* tc_spo01@wp-p2m-41:/mnt/data/biosamples/sw/www/
    - scp -r -v -o StrictHostKeyChecking=no config/* tc_spo01@wp-p2m-41:/mnt/data/biosamples/
    - scp -r -v -o StrictHostKeyChecking=no /mnt/data/biosamples/sw/www/wp-p2m-41/ tc_spo01@wp-p2m-40:/mnt/data/biosamples/sw/www/
    # mark all scripts as executable
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'chmod ug+x /mnt/data/biosamples/sw/www/*.sh'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'chmod ug+x /mnt/data/biosamples/servers/*/*/*.sh'
    # monit config
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'chmod 0700 /mnt/data/biosamples/servers/monit/*/monit.conf'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'mkdir -p /mnt/data/biosamples/logs/monit/wp-p2m-41.2812'
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'mkdir -p /mnt/data/biosamples/data/monit/wp-p2m-41.2812'
    # install cron script
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 'crontab /mnt/data/biosamples/servers/crontab.wp-p2m-41.conf'
    # start up and monitor everything
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 '/mnt/data/biosamples/servers/monit/wp-p2m-41.2812/start.sh'
    - sleep 15
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 '/mnt/data/biosamples/servers/monit/wp-p2m-41.2812/monit.sh start all'
    # poll for services
    - sleep 300
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p2m-41 /mnt/data/biosamples/sw/www/http-status-check -t 3600 -u 'http://wp-p2m-41.ebi.ac.uk:8081/biosamples/health'
  when: manual
  only:
    - master

deploy-production-p1m-servers:
    image: ubuntu
    stage: deploy
    script:
      - ls deployment/
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
      - eval $(ssh-agent -s)
      - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      # deploy to wp-p1m-40
      # stop running services
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 '/mnt/data/biosamples/servers/monit/wp-p1m-40.2812/monit.sh stop agents-solr'
      - sleep 60
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 '/mnt/data/biosamples/servers/monit/wp-p1m-40.2812/monit.sh stop webapps-core'
      - sleep 60
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 '/mnt/data/biosamples/servers/monit/wp-p1m-40.2812/stop.sh'
      - sleep 60
      # remove old artifacts
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'rm -rf /mnt/data/biosamples/sw/www/*.jar'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'rm -rf /mnt/data/biosamples/sw/www/*.war'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'rm -rf /mnt/data/biosamples/sw/www/*.sh'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'rm -rf /mnt/data/biosamples/sw/www/*.js'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'rm -rf /mnt/data/biosamples/sw/www/*.py'
      # Copy scripts and other config
      - scp -r -v -o StrictHostKeyChecking=no deployment/* tc_spo01@wp-p1m-40:/mnt/data/biosamples/sw/www/
      - scp -r -v -o StrictHostKeyChecking=no config/* tc_spo01@wp-p1m-40:/mnt/data/biosamples/
      - scp -r -v -o StrictHostKeyChecking=no /mnt/data/biosamples/sw/www/wp-p1m-40/ tc_spo01@wp-p2m-40:/mnt/data/biosamples/sw/www/
      # mark all scripts as executable
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'chmod ug+x /mnt/data/biosamples/sw/www/*.sh'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'chmod ug+x /mnt/data/biosamples/servers/*/*/*.sh'
      # monit config
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'chmod 0700 /mnt/data/biosamples/servers/monit/*/monit.conf'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'mkdir -p /mnt/data/biosamples/logs/monit/wp-p1m-40.2812'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'mkdir -p /mnt/data/biosamples/data/monit/wp-p1m-40.2812'
      # install cron script
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 'crontab /mnt/data/biosamples/servers/crontab.wp-p1m-40.conf'
      # start up and monitor everything
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 '/mnt/data/biosamples/servers/monit/wp-p1m-40.2812/start.sh'
      - sleep 15
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 '/mnt/data/biosamples/servers/monit/wp-p1m-40.2812/monit.sh start all'
      # poll for services
      - sleep 300
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-40 /mnt/data/biosamples/sw/www/http-status-check -t 3600 -u 'http://wp-p1m-40.ebi.ac.uk:8081/biosamples/health'
      # deploy to wp-p1m-41
      # stop running services
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 '/mnt/data/biosamples/servers/monit/wp-p1m-41.2812/monit.sh stop agents-solr'
      - sleep 60
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 '/mnt/data/biosamples/servers/monit/wp-p1m-41.2812/monit.sh stop webapps-core'
      - sleep 60
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 '/mnt/data/biosamples/servers/monit/wp-p1m-41.2812/stop.sh'
      - sleep 60
      # remove old artifacts
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'rm -rf /mnt/data/biosamples/sw/www/*.jar'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'rm -rf /mnt/data/biosamples/sw/www/*.war'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'rm -rf /mnt/data/biosamples/sw/www/*.sh'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'rm -rf /mnt/data/biosamples/sw/www/*.js'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'rm -rf /mnt/data/biosamples/sw/www/*.py'
      # Copy scripts and other config
      - scp -r -v -o StrictHostKeyChecking=no deployment/* tc_spo01@wp-p1m-41:/mnt/data/biosamples/sw/www/
      - scp -r -v -o StrictHostKeyChecking=no config/* tc_spo01@wp-p1m-41:/mnt/data/biosamples/
      - scp -r -v -o StrictHostKeyChecking=no /mnt/data/biosamples/sw/www/wp-p1m-41/ tc_spo01@wp-p2m-40:/mnt/data/biosamples/sw/www/
      # mark all scripts as executable
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'chmod ug+x /mnt/data/biosamples/sw/www/*.sh'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'chmod ug+x /mnt/data/biosamples/servers/*/*/*.sh'
      # monit config
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'chmod 0700 /mnt/data/biosamples/servers/monit/*/monit.conf'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'mkdir -p /mnt/data/biosamples/logs/monit/wp-p1m-41.2812'
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'mkdir -p /mnt/data/biosamples/data/monit/wp-p1m-41.2812'
      # install cron script
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 'crontab /mnt/data/biosamples/servers/crontab.wp-p1m-41.conf'
      # start up and monitor everything
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 '/mnt/data/biosamples/servers/monit/wp-p1m-41.2812/start.sh'
      - sleep 15
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 '/mnt/data/biosamples/servers/monit/wp-p1m-41.2812/monit.sh start all'
      # poll for services
      - sleep 300
      - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m-41 /mnt/data/biosamples/sw/www/http-status-check -t 3600 -u 'http://wp-p1m-41.ebi.ac.uk:8081/biosamples/health'
    when: manual
    only:
      - master
