image: docker:stable
services:
  - docker:stable-dind

variables:
  DEPLOY_PATH: ~/gitlab
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret
  APP_NAME: $CI_PROJECT_NAME
  K8S_NAMESPACE_PREFIX: biosamples

before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - apk update && apk add git

stages:
  - build
  - package
  - config
  - deploy

maven-package-all-apps:
  image: ${CI_REGISTRY_IMAGE}/eclipse-temurin:17-jdk
  stage: build
  script:
    - './mvnw -q package -P embl-ebi -s ci_settings.xml -DskipTests -Dmaven.source.skip=true'
  artifacts:
    paths:
      - webapps/core/target/webapps-core-*.war
      - webapps/core-v2/target/webapps-core-v2-*.jar
      - agents/uploadworkers/target/agents-uploadworkers-*.jar
      - pipelines/reindex/target/pipelines-reindex-*.jar


build_and_push_docker_images:
  stage: package
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  parallel:
    matrix:
      - APP_NAME: "webapp-core"
        DOCKERFILE_TARGET: "webapp-core"
      - APP_NAME: "webapp-core-v2"
        DOCKERFILE_TARGET: "webapp-core-v2"
      - APP_NAME: "agents-uploadworkers"
        DOCKERFILE_TARGET: "agents-uploadworkers"
      - APP_NAME: "pipelines-reindex"
        DOCKERFILE_TARGET: "pipelines-reindex"
  script:
    - |
      DOCKER_IMAGE_NAME="$CI_REGISTRY_IMAGE/$APP_NAME:$DOCKER_TAG"
      echo "Building and pushing $DOCKER_IMAGE_NAME with target $DOCKERFILE_TARGET"
      docker build --target $DOCKERFILE_TARGET -t $DOCKER_IMAGE_NAME -f k8s/Dockerfile .
      docker push $DOCKER_IMAGE_NAME
      
      # Also tag as latest for the current branch
      DOCKER_LATEST_NAME="$CI_REGISTRY_IMAGE/$APP_NAME:$CI_COMMIT_REF_SLUG-latest"
      docker tag $DOCKER_IMAGE_NAME $DOCKER_LATEST_NAME
      docker push $DOCKER_LATEST_NAME
      echo $DOCKER_LATEST_NAME
  after_script:
    - docker logout $CI_REGISTRY


deploy_k8s_primary_dev:
  variables:
    ENVIRONMENT_NAME: primary_dev
    K8S_NAMESPACE: biosamples-dev
  environment:
    name: primary_dev
    url: https://wwwdev.ebi.ac.uk/biosamples
  only:
    - dev
    - main
    - biosamples-search
  when: manual
  extends: .kube_deploy_script

deploy_k8s_primary_prod:
  variables:
    ENVIRONMENT_NAME: primary_prod
    K8S_NAMESPACE: biosamples-prod
  environment:
    name: primary_prod
    url: https://www.ebi.ac.uk/biosamples
  only:
    - dev
    - main
    - biosamples-search
  when: manual
  extends: .kube_deploy_script

deploy_k8s_fallback_prod:
  variables:
    ENVIRONMENT_NAME: fallback_prod
    K8S_NAMESPACE: biosamples-prod
  environment:
    name: fallback_prod
    url: https://www.ebi.ac.uk/biosamples
  only:
    - dev
    - main
    - biosamples-search
  when: manual
  extends: .kube_deploy_script

deploy_pipeline_k8s_primary_prod:
  variables:
    ENVIRONMENT_NAME: primary_prod
    K8S_NAMESPACE: biosamples-prod
  environment:
    name: primary_prod
    url: https://wwwdev.ebi.ac.uk/biosamples
  only:
    - dev
    - main
    - biosamples-search
  when: manual
  extends: .kube_deploy_jobs_script

deploy_pipeline_k8s_primary_dev:
  variables:
    ENVIRONMENT_NAME: primary_dev
    K8S_NAMESPACE: biosamples-dev
  environment:
    name: primary_dev
    url: https://wwwdev.ebi.ac.uk/biosamples
  only:
    - dev
    - main
    - biosamples-search
  when: manual
  extends: .kube_deploy_jobs_script

deploy_cronjobs_k8s_primary_dev:
  variables:
    ENVIRONMENT_NAME: primary_dev
    K8S_NAMESPACE: biosamples-dev
  environment:
    name: primary_dev
    url: https://wwwdev.ebi.ac.uk/biosamples
  only:
    - dev
    - main
    - biosamples-search
  when: manual
  extends: .kube_deploy_cronjobs_script

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl:3.16
  tags: ["dind"]
  services:
    - docker:27-dind
  script:
    - echo $K8S_NAMESPACE
    - kubectl config view
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - |
      kubectl create secret docker-registry $DOCKER_PULL_SECRET \
              --docker-server=$CI_REGISTRY \
              --docker-username=$CI_REGISTRY_USER \
              --docker-password=$CI_REGISTRY_PASSWORD
    - |
      helm upgrade --install $APP_NAME ./k8s/helm \
                   --values ./k8s/helm/values-${ENVIRONMENT_NAME}.yaml \
                   --set "imagePullSecrets[0].name=$DOCKER_PULL_SECRET" \
                   --set image.repository=$CI_REGISTRY_IMAGE/webapp-core \
                   --set image.tag=$DOCKER_TAG \
                   --set biosamples.context.path=/biosamples
    - |
      helm upgrade --install ${APP_NAME}-v2 ./k8s/helm \
                   --values ./k8s/helm/values-${ENVIRONMENT_NAME}.yaml \
                   --set "imagePullSecrets[0].name=$DOCKER_PULL_SECRET" \
                   --set image.repository=$CI_REGISTRY_IMAGE/webapp-core-v2 \
                   --set image.tag=$DOCKER_TAG \
                   --set biosamples.context.path=/biosamples/v2
    - |
      helm upgrade --install ${APP_NAME}-uploadworkers ./k8s/helm \
                   --values ./k8s/helm/values-${ENVIRONMENT_NAME}.yaml \
                   --set "imagePullSecrets[0].name=$DOCKER_PULL_SECRET" \
                   --set image.repository=$CI_REGISTRY_IMAGE/webapp-core-v2 \
                   --set image.tag=$DOCKER_TAG 

.kube_deploy_jobs_script:
  stage: deploy
  image: dtzar/helm-kubectl:3.16
  tags: [ "dind" ]
  services:
    - docker:27-dind
  script:
    - echo $K8S_NAMESPACE
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - |
      kubectl create secret docker-registry $DOCKER_PULL_SECRET \
              --docker-server=$CI_REGISTRY \
              --docker-username=$CI_REGISTRY_USER \
              --docker-password=$CI_REGISTRY_PASSWORD
    - |
      helm upgrade --install biosamples-reindex ./k8s/jobs \
                   --values ./k8s/jobs/values-${ENVIRONMENT_NAME}.yaml \
                   --set "imagePullSecrets[0].name=$DOCKER_PULL_SECRET" \
                   --set image.repository=$CI_REGISTRY_IMAGE/pipelines-reindex \
                   --set image.tag=$DOCKER_TAG

.kube_deploy_cronjobs_script:
  stage: deploy
  image: dtzar/helm-kubectl:3.16
  tags: [ "dind" ]
  services:
    - docker:27-dind
  script:
    - echo $K8S_NAMESPACE
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - |
      kubectl create secret docker-registry $DOCKER_PULL_SECRET \
              --docker-server=$CI_REGISTRY \
              --docker-username=$CI_REGISTRY_USER \
              --docker-password=$CI_REGISTRY_PASSWORD
    - |
      helm upgrade --install biosamples-reindex ./k8s/cronjobs \
                   --values ./k8s/cronjobs/values-${ENVIRONMENT_NAME}.yaml \
                   --set "imagePullSecrets[0].name=$DOCKER_PULL_SECRET" \
                   --set image.repository=$CI_REGISTRY_IMAGE/pipelines-curation \
                   --set image.tag=$DOCKER_TAG
