image: docker:latest

variables:
  DEPLOY_PATH: ~/gitlab

before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR

stages:
  - package
  - config
  - deploy

maven-package:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/maven:3.6-jdk-11
  stage: package
  script:
    - 'mvn -q deploy -P embl-ebi -s ci_settings.xml -Dmaven.source.skip=true'
    - mkdir deployment
    - cp webapps/core/target/webapps-core-*.war deployment/webapps-core.war
    - cp webapps/core-v2/target/webapps-core-v2*.jar deployment/webapps-core-v2.jar
    - cp agents/solr/target/agents-solr-*.jar deployment/agents-solr.jar
    - cp agents/uploadworkers/target/agents-uploadworkers-*.jar deployment/agents-uploadworkers.jar
    - cp pipelines/copydown/target/pipelines-copydown-*.jar pipelines/pipelines-copydown.jar
    - cp pipelines/curami/target/pipelines-curami-*.jar pipelines/pipelines-curami.jar
    - cp pipelines/curation/target/pipelines-curation-*.jar pipelines/pipelines-curation.jar
    - cp pipelines/ena/target/pipelines-ena-*.jar pipelines/pipelines-ena.jar
    - cp pipelines/sample-release/target/pipelines-sample-release-*.jar pipelines/pipelines-sample-release.jar
    - cp pipelines/export/target/pipelines-export-*.jar pipelines/pipelines-export.jar
    - cp pipelines/ncbi/target/pipelines-ncbi-*.jar pipelines/pipelines-ncbi.jar
    - cp pipelines/neoexport/target/pipelines-neoexport-*.jar pipelines/pipelines-neoexport.jar
    - cp pipelines/reindex/target/pipelines-reindex-*.jar pipelines/pipelines-reindex.jar
    - cp pipelines/zooma/target/pipelines-zooma-*.jar pipelines/pipelines-zooma.jar
    - cp pipelines/sample-transformation-dtol/target/pipelines-sample-transformation-dtol-*.jar pipelines/pipelines-sample-transformation-dtol.jar
  artifacts:
    paths:
      - deployment
      - pipelines
#  when: manual

clone-config-preproduction:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/maven:3.6-jdk-11
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/biosamples-internal.git
    - mkdir config
    - cp -r biosamples-internal/script/* deployment/
    - cp -r biosamples-internal/wwwdev/* config/
    - cp biosamples-internal/deployment/deploy.sh ./
  artifacts:
    paths:
      - deployment
      - config
      - deploy.sh
  when: manual

clone-config-production:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/maven:3.6-jdk-11
  stage: config
  script:
    - git clone https://$BSD_INTERNAL_USER:$BSD_INTERNAL_PASS@gitlab.ebi.ac.uk/biosamples/biosamples-internal.git
    - mkdir config
    - cp -r biosamples-internal/script/* deployment/
    - cp -r biosamples-internal/www/* config/
    - cp biosamples-internal/deployment/deploy.sh ./
  artifacts:
    paths:
      - deployment
      - config
      - deploy.sh
  when: manual
  only:
    - master

deploy-preproduction:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/ubuntu
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh bsd_dev wp-np2-40
  when: manual
  only:
    - gitlab_ci_improvements
    - dev
    - master

deploy-production-p2m-servers:
  image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/ubuntu
  stage: deploy
  script:
    - chmod +x deploy.sh
    - ./deploy.sh bsd_prod wp-p2m-40
    - ./deploy.sh bsd_prod wp-p2m-41
  when: manual
  only:
    - master

deploy-production-p1m-servers:
    image: dockerhub.ebi.ac.uk/biosamples/biosamples-v4/ubuntu
    stage: deploy
    script:
      - chmod +x deploy.sh
      - ./deploy.sh bsd_prod wp-p1m-40
      - ./deploy.sh bsd_prod wp-p1m-41
    when: manual
    only:
      - master
