v4.2.1 Release Notes
----------------------------
New features:
-------------------
1. Handler added to check and update sample status in BioSamples for SUPPRESSED samples in ENA/NCBI. SUPPRESSED samples that exist in ENA and not in BioSamples are created in BioSamples. This helps to have a consistent view of the samples in ENA and BioSamples.
2. Contact full details will be saved and displayed by default, which includes name, role, email, affiliation etc. Request param -setfulldetails if set false and passed in the request URI, full details of contact won’t be saved.
3. ENA BioSamples integration changes has been done in this release. This will enable ENA presentation to query BioSamples API for the samples metadata. 
Short description of the changes done are given below:
	1. Retaining of ArrayExpress elements in ENA imported samples
	2. Mapping of alias in ENA sample XML to name (top-attribute) in BioSamples JSON
	3. Mapping of SAMPLE_ATTRIBUTE/alias in ENA sample XML to characteristics/alias in BioSamples JSON
	4. Removing tagging of core attributes from Synonyms for ENA/NCBI/DDBJ samples. SUBMITTER_ID, EXTERNAL_ID, UUID, ANONYMIZED_NAME, INDIVIDUAL_NAME attributes were earlier mapped to synonyms. With this release they are mapped to individual attributes under characteristics in BioSamples JSON, like characteristics/External Id, characteristics/Submitter Id and so on
	5. Introduction of tag in BioSamples JSON for mapping namespace values in ENA/NCBI/DDBJ samples. An example below:
	External_id" : [{ 
	"text" : "GM18582", 
	“tag” : “Namespace: Coriell” 
	} ]
	"Submitter Id" : [ {
      	"text" : "ZF_CR_MPX22_279-sc-2227782",
      	"tag" : "Namespace:SC"
    	} ]

	6. Handling for multiple descriptions (core description and SAMPLE_ATTRIBUTE description) for ENA/NCBI/DDBJ samples. An example below. Reusing of tag to show if the description is of core or sample attributes
	"Description" : [
	{ "text" : "Protocols: U2OS cells .....)", "tag" : "core" },
	{ "text" : "This sample has been re-named", "tag" : "attribute" }
	]

	7. Removing characteristics/synonym from BioSamples JSON for ENA/NCBI/DDBJ samples. All attributes that were tagged under synonyms now has individual attributes under characteristics and hence synonym is not required. Alias is now mapped to name too and hence it makes synonym redundant
	8. PRIMARY_ID of NCBI/DDBJ samples mapped to characteristics/SRA accession in BioSamples JSON. This will bring samples metadata in BioSamples in sync for ENA/NCBI/DDBJ samples. 
	9. Title was mapped to characteristics/Title (for ENA samples) and characteristics/description title (for NCBI/DDBJ samples). Title is now mapped to characteristics/Title for all ENA/NCBI/DDBJ samples
	10. GenBank common name handled in characteristics/Common Name for NCBI/DDBJ samples. Provision is kept for ENA samples too if such an attribute exists.
	11. Performance improvements of ENA pipeline
	12. Create date added for ENA/NCBI/DDBJ samples
	13. Retaining of ENA prefixed attributes in BioSamples JSON

Bug fixes:
-------------
1.	UI bugfix to display contact role. Earlier it used to show name instead of role.
2.  Change curation-view pipeline to read samples from MongDB. To crawl all the samples available in BIoSamples, we can’t use biosamples-client get all samples method as it will not return non-indexed samples (eg. suppressed samples) 
