
= [.ebi-color]#How to retrieve sample without any curations or only specified curations#
:last-update-label!:

== User requirements
I want to retrieve samples without any curations or only apply selected curations.

== Limitations
- You can only use BioSamples JSON API for retrieving samples with different curation domains.

== Usecases

=== 1. Retrieve sample without any curations
Providing an `applyCurations=false` query parameter will instruct BioSamples to remove all curations applied on top of the original sample.

Example `curl` command:
```shell
curl 'https://www.ebi.ac.uk/biosamples/samples/SAMEA9948714?applyCurations=false' -i -X GET -H "Accept: application/json"
```

=== Viewing curations
You can also view all the curations applied to a particular samples using `curationlinks` endpoint
```shell
curl 'https://www.ebi.ac.uk/biosamples/samples/SAMEA9948714/curationlinks' -i -X GET -H "Accept: application/json"
```

In the given example you can see sample `SAMEA9948714` has 5 curations applied to it (at current time).
In this sample, all curations are automatic curations applied by BioSamples curation pipelines.
