/*
* Copyright 2021 EMBL - European Bioinformatics Institute
* Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
* file except in compliance with the License. You may obtain a copy of the License at
* http://www.apache.org/licenses/LICENSE-2.0
* Unless required by applicable law or agreed to in writing, software distributed under the
* License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
* CONDITIONS OF ANY KIND, either express or implied. See the License for the
* specific language governing permissions and limitations under the License.
*/
package uk.ac.ebi.biosamples.ena;

public class ExampleSamples {

  public static String exampleSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE alias=\"K510\" center_name=\"UNIBE-IG\" accession=\"ERS2295402\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>ERS2295402</PRIMARY_ID>\n"
          + "         <SUBMITTER_ID namespace=\"UNIBE-IG\">K510</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>unknown/stray cat</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9685</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>\n"
          + "         <COMMON_NAME>domestic cat</COMMON_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>unknown/stray cat female</DESCRIPTION>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>ENA-CHECKLIST</TAG>\n"
          + "            <VALUE>ERC000011</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String exampleSampleWithoutTitleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE accession=\"ERS000003\" alias=\"Solexa sequencing of Saccharomyces cerevisiae strain W303 random 200 bp library\" center_name=\"SC\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>ERS000003</PRIMARY_ID>\n"
          + "         <SUBMITTER_ID namespace=\"SC\">Solexa sequencing of Saccharomyces cerevisiae strain W303 random 200 bp library</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>580240</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Saccharomyces cerevisiae W303</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>Solexa sequencing of Saccharomyces cerevisiae strain W303 random 200 bp library</DESCRIPTION>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>strain</TAG>\n"
          + "            <VALUE>W303</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String exampleSampleThatCanBeTaxonFixedSAMN02356578 =
      "<SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"Broad Institute\" alias=\"Acinetobacter lwoffii CIP64.10\" accession=\"SRS485026\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>SRS485026</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMN02356578</EXTERNAL_ID>\n"
          + "         <EXTERNAL_ID namespace=\"Broad Institute\" label=\"Sample name\">Acinetobacter lwoffii CIP64.10</EXTERNAL_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>General Sample for Acinetobacter lwoffii NIPH 512</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>1400346</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Acinetobacter lwoffii NIPH 512</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <SAMPLE_LINKS>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <XREF_LINK>\n"
          + "               <DB>bioproject</DB>\n"
          + "               <ID>219244</ID>\n"
          + "            </XREF_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "      </SAMPLE_LINKS>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>collection_date</TAG>\n"
          + "            <VALUE>2011</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>geo_loc_name</TAG>\n"
          + "            <VALUE>Unknown</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>specific_host</TAG>\n"
          + "            <VALUE>Homo sapiens</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>isolation_source</TAG>\n"
          + "            <VALUE>Unknown</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>strain</TAG>\n"
          + "            <VALUE>NIPH 512</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String exampleSampleThatCanBeTaxonFixed =
      "<SAMPLE_SET>\n"
          + "   <SAMPLE alias=\"BCM-DGRP301\" center_name=\"BCM\" accession=\"SRS003443\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>SRS003443</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMN00014227</EXTERNAL_ID>\n"
          + "         <SUBMITTER_ID namespace=\"BCM\">BCM-DGRP301</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>Drosophila melanogaster DGRP-301</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>7227</TAXON_ID>\n"
          + "         <COMMON_NAME>Drosophila melanogaster</COMMON_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>Drosophila melanogaster DGRP-301</DESCRIPTION>\n"
          + "      <SAMPLE_LINKS>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>Drosophila Genetic Reference Panel at Baylor College of Medicine</LABEL>\n"
          + "               <URL>https://www.hgsc.bcm.edu/content/drosophila-genetic-reference-panel</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>SAMN00014227</LABEL>\n"
          + "               <URL>https://www.hgsc.bcm.edu/content/drosophila-genetic-reference-panel</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "      </SAMPLE_LINKS>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Strain</TAG>\n"
          + "            <VALUE>DGRP-301</VALUE>\n"
          + "            <UNITS/>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String exampleSampleWithTitleAddedXml =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE accession=\"ERS000003\" alias=\"Solexa sequencing of Saccharomyces cerevisiae strain W303 random 200 bp library\" center_name=\"SC\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>ERS000003</PRIMARY_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"SC\">Solexa sequencing of Saccharomyces cerevisiae strain W303 random 200 bp library</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>580240</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Saccharomyces cerevisiae W303</SCIENTIFIC_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>Solexa sequencing of Saccharomyces cerevisiae strain W303 random 200 bp library</DESCRIPTION>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>strain</TAG>  \n"
          + "        <VALUE>W303</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES>  \n"
          + "    <TITLE>Saccharomyces cerevisiae W303</TITLE>\n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String missingAliasSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"UNIBE-IG\" accession=\"ERS2295402\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>ERS2295402</PRIMARY_ID>\n"
          + "         <SUBMITTER_ID namespace=\"UNIBE-IG\">K510</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>unknown/stray cat</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9685</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>\n"
          + "         <COMMON_NAME>domestic cat</COMMON_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>unknown/stray cat female</DESCRIPTION>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>ENA-CHECKLIST</TAG>\n"
          + "            <VALUE>ERC000011</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String expectedModifiedMissingAliasSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"UNIBE-IG\" accession=\"ERS2295402\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>ERS2295402</PRIMARY_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>unknown/stray cat</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9685</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>\n"
          + "         <COMMON_NAME>domestic cat</COMMON_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>unknown/stray cat female</DESCRIPTION>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>ENA-CHECKLIST</TAG>\n"
          + "            <VALUE>ERC000011</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String missingNamespaceSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE alias=\"K510\" center_name=\"UNIBE-IG\" accession=\"ERS2295402\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>ERS2295402</PRIMARY_ID>\n"
          + "         <SUBMITTER_ID>K510</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>unknown/stray cat</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9685</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>\n"
          + "         <COMMON_NAME>domestic cat</COMMON_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>unknown/stray cat female</DESCRIPTION>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>ENA-CHECKLIST</TAG>\n"
          + "            <VALUE>ERC000011</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String emptyNamespaceSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE alias=\"K510\" center_name=\"UNIBE-IG\" accession=\"ERS2295402\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>ERS2295402</PRIMARY_ID>\n"
          + "         <SUBMITTER_ID namespace=\"\">K510</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>unknown/stray cat</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9685</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>\n"
          + "         <COMMON_NAME>domestic cat</COMMON_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>unknown/stray cat female</DESCRIPTION>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>ENA-CHECKLIST</TAG>\n"
          + "            <VALUE>ERC000011</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String expectedModifiedNcbiBrokerSampleXml =
      "<SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"1000G\" alias=\"NA18561\" accession=\"SRS000121\" broker_name=\"NCBI\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>SRS000121</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMN00001603</EXTERNAL_ID>\n"
          + "         <EXTERNAL_ID namespace=\"Coriell\">GM18561</EXTERNAL_ID>\n"
          + "         <SUBMITTER_ID namespace=\"1000G\">NA18561</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>Coriell GM18561</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9606</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Homo sapiens</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>Human HapMap individual Coriell catalog ID NA18561</DESCRIPTION>\n"
          + "      <SAMPLE_LINKS>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>dbSNP Batch ID 1061891</LABEL>\n"
          + "               <URL>http://www.ncbi.nlm.nih.gov/SNP/snp_viewBatch.cgi?sbid=1061891</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>Individual record in dbSNP</LABEL>\n"
          + "               <URL>http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ind.cgi?ind_id=5153</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "      </SAMPLE_LINKS>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>DNA-ID</TAG>\n"
          + "            <VALUE>NA18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Super Population Code</TAG>\n"
          + "            <VALUE>EAS</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>population</TAG>\n"
          + "            <VALUE>CHB</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Super Population Description</TAG>\n"
          + "            <VALUE>East Asian</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Coriell plate</TAG>\n"
          + "            <VALUE>HAPMAPPT02</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Coriell panel</TAG>\n"
          + "            <VALUE>MGP00017</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Population Description</TAG>\n"
          + "            <VALUE>Han Chinese in Beijing, China</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sex</TAG>\n"
          + "            <VALUE>male</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>HapMap sample ID</TAG>\n"
          + "            <VALUE>NA18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>culture_collection</TAG>\n"
          + "            <VALUE>Coriell:GM18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>BioSampleModel</TAG>\n"
          + "            <VALUE>HapMap</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String ncbiSampleXml =
      "<SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"1000G\" alias=\"NA18561\" accession=\"SRS000121\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>SRS000121</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMN00001603</EXTERNAL_ID>\n"
          + "         <EXTERNAL_ID namespace=\"Coriell\">GM18561</EXTERNAL_ID>\n"
          + "         <SUBMITTER_ID namespace=\"1000G\">NA18561</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>Coriell GM18561</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9606</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Homo sapiens</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>Human HapMap individual Coriell catalog ID NA18561</DESCRIPTION>\n"
          + "      <SAMPLE_LINKS>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>dbSNP Batch ID 1061891</LABEL>\n"
          + "               <URL>http://www.ncbi.nlm.nih.gov/SNP/snp_viewBatch.cgi?sbid=1061891</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>Individual record in dbSNP</LABEL>\n"
          + "               <URL>http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ind.cgi?ind_id=5153</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "      </SAMPLE_LINKS>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>DNA-ID</TAG>\n"
          + "            <VALUE>NA18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Super Population Code</TAG>\n"
          + "            <VALUE>EAS</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>population</TAG>\n"
          + "            <VALUE>CHB</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Super Population Description</TAG>\n"
          + "            <VALUE>East Asian</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Coriell plate</TAG>\n"
          + "            <VALUE>HAPMAPPT02</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Coriell panel</TAG>\n"
          + "            <VALUE>MGP00017</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Population Description</TAG>\n"
          + "            <VALUE>Han Chinese in Beijing, China</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sex</TAG>\n"
          + "            <VALUE>male</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>HapMap sample ID</TAG>\n"
          + "            <VALUE>NA18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>culture_collection</TAG>\n"
          + "            <VALUE>Coriell:GM18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>BioSampleModel</TAG>\n"
          + "            <VALUE>HapMap</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String ddbjSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"BioSample\" alias=\"SAMD00015737\" accession=\"DRS000378\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>DRS000378</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMD00015737</EXTERNAL_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>Ovarian piRNAs from a female that shows W chromosome mutation linked sex differentiation deficiency (Individual No. 4-1)</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>7091</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Bombyx mori</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sample_name</TAG>\n"
          + "            <VALUE>DRS000378</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sex</TAG>\n"
          + "            <VALUE>female</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sample comment</TAG>\n"
          + "            <VALUE>piRNA library was constructed from say 4 pupal ovary from a female that shows sex differentiation deficiency</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>dev_stage</TAG>\n"
          + "            <VALUE>4 day old pupa</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>cell type</TAG>\n"
          + "            <VALUE>ovary</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String expectedModifiedDdbjBrokerSampleXml =
      "<?xml version = '1.0' encoding = 'UTF-8'?><SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"BioSample\" alias=\"SAMD00015737\" accession=\"DRS000378\" broker_name=\"DDBJ\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>DRS000378</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMD00015737</EXTERNAL_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>Ovarian piRNAs from a female that shows W chromosome mutation linked sex differentiation deficiency (Individual No. 4-1)</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>7091</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Bombyx mori</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sample_name</TAG>\n"
          + "            <VALUE>DRS000378</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sex</TAG>\n"
          + "            <VALUE>female</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sample comment</TAG>\n"
          + "            <VALUE>piRNA library was constructed from say 4 pupal ovary from a female that shows sex differentiation deficiency</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>dev_stage</TAG>\n"
          + "            <VALUE>4 day old pupa</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>cell type</TAG>\n"
          + "            <VALUE>ovary</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String expectedModifiedNcbiLinksRemoved =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE center_name=\"1000G\" alias=\"NA18561\" accession=\"SRS000121\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>SRS000121</PRIMARY_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"BioSample\">SAMN00001603</EXTERNAL_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"Coriell\">GM18561</EXTERNAL_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"1000G\">NA18561</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>Coriell GM18561</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>9606</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Homo sapiens</SCIENTIFIC_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>Human HapMap individual Coriell catalog ID NA18561</DESCRIPTION>  \n"
          + "    <SAMPLE_LINKS></SAMPLE_LINKS>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>DNA-ID</TAG>  \n"
          + "        <VALUE>NA18561</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Super Population Code</TAG>  \n"
          + "        <VALUE>EAS</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>population</TAG>  \n"
          + "        <VALUE>CHB</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Super Population Description</TAG>  \n"
          + "        <VALUE>East Asian</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Coriell plate</TAG>  \n"
          + "        <VALUE>HAPMAPPT02</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Coriell panel</TAG>  \n"
          + "        <VALUE>MGP00017</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Population Description</TAG>  \n"
          + "        <VALUE>Han Chinese in Beijing, China</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>sex</TAG>  \n"
          + "        <VALUE>male</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>HapMap sample ID</TAG>  \n"
          + "        <VALUE>NA18561</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>culture_collection</TAG>  \n"
          + "        <VALUE>Coriell:GM18561</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>BioSampleModel</TAG>  \n"
          + "        <VALUE>HapMap</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String exampleSampleXmlWithDates =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE alias=\"K510\" center_name=\"UNIBE-IG\" accession=\"ERS2295402\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>ERS2295402</PRIMARY_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"UNIBE-IG\">K510</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>unknown/stray cat</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>9685</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>  \n"
          + "      <COMMON_NAME>domestic cat</COMMON_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>unknown/stray cat female</DESCRIPTION>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>ENA-CHECKLIST</TAG>  \n"
          + "        <VALUE>ERC000011</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE>\n"
          + "        <TAG>ENA-FIRST-PUBLIC</TAG>\n"
          + "        <VALUE>2018-01-01</VALUE>\n"
          + "      </SAMPLE_ATTRIBUTE>\n"
          + "      <SAMPLE_ATTRIBUTE>\n"
          + "        <TAG>ENA-LAST-UPDATE</TAG>\n"
          + "        <VALUE>2018-02-01</VALUE>\n"
          + "      </SAMPLE_ATTRIBUTE>\n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String expectedModifiedEbiBrokerSampleXml =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE alias=\"K510\" center_name=\"UNIBE-IG\" accession=\"ERS2295402\" broker_name=\"broker\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>ERS2295402</PRIMARY_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"UNIBE-IG\">K510</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>unknown/stray cat</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>9685</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>  \n"
          + "      <COMMON_NAME>domestic cat</COMMON_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>unknown/stray cat female</DESCRIPTION>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>ENA-CHECKLIST</TAG>  \n"
          + "        <VALUE>ERC000011</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String expectedModifiedEbiBiosamplesSampleXml =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE alias=\"K510\" center_name=\"UNIBE-IG\" accession=\"ERS2295402\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>ERS2295402</PRIMARY_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"UNIBE-IG\">K510</SUBMITTER_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"BioSample\">SAMN00001603</EXTERNAL_ID>\n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>unknown/stray cat</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>9685</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>  \n"
          + "      <COMMON_NAME>domestic cat</COMMON_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>unknown/stray cat female</DESCRIPTION>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>ENA-CHECKLIST</TAG>  \n"
          + "        <VALUE>ERC000011</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String expectedModifiedCenterNameSampleXml =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE alias=\"K510\" center_name=\"expanded center name\" accession=\"ERS2295402\" center_alias=\"UNIBE-IG\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>ERS2295402</PRIMARY_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"UNIBE-IG\">K510</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>unknown/stray cat</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>9685</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Felis catus</SCIENTIFIC_NAME>  \n"
          + "      <COMMON_NAME>domestic cat</COMMON_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>unknown/stray cat female</DESCRIPTION>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>ENA-CHECKLIST</TAG>  \n"
          + "        <VALUE>ERC000011</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String fullSampleXml =
      "<SAMPLE_SET>\n"
          + "   <SAMPLE center_name=\"1000G\" alias=\"NA18561\" accession=\"SRS000121\">\n"
          + "      <IDENTIFIERS>\n"
          + "         <PRIMARY_ID>SRS000121</PRIMARY_ID>\n"
          + "         <EXTERNAL_ID namespace=\"BioSample\">SAMN00001603</EXTERNAL_ID>\n"
          + "         <EXTERNAL_ID namespace=\"Coriell\">GM18561</EXTERNAL_ID>\n"
          + "         <SUBMITTER_ID namespace=\"1000G\">NA18561</SUBMITTER_ID>\n"
          + "      </IDENTIFIERS>\n"
          + "      <TITLE>Coriell GM18561</TITLE>\n"
          + "      <SAMPLE_NAME>\n"
          + "         <TAXON_ID>9606</TAXON_ID>\n"
          + "         <SCIENTIFIC_NAME>Homo sapiens</SCIENTIFIC_NAME>\n"
          + "      </SAMPLE_NAME>\n"
          + "      <DESCRIPTION>Human HapMap individual Coriell catalog ID NA18561</DESCRIPTION>\n"
          + "      <SAMPLE_LINKS>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>dbSNP Batch ID 1061891</LABEL>\n"
          + "               <URL>http://www.ncbi.nlm.nih.gov/SNP/snp_viewBatch.cgi?sbid=1061891</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "         <SAMPLE_LINK>\n"
          + "            <URL_LINK>\n"
          + "               <LABEL>Individual record in dbSNP</LABEL>\n"
          + "               <URL>http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ind.cgi?ind_id=5153</URL>\n"
          + "            </URL_LINK>\n"
          + "         </SAMPLE_LINK>\n"
          + "      </SAMPLE_LINKS>\n"
          + "      <SAMPLE_ATTRIBUTES>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>DNA-ID</TAG>\n"
          + "            <VALUE>NA18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Super Population Code</TAG>\n"
          + "            <VALUE>EAS</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>population</TAG>\n"
          + "            <VALUE>CHB</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Super Population Description</TAG>\n"
          + "            <VALUE>East Asian</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Coriell plate</TAG>\n"
          + "            <VALUE>HAPMAPPT02</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Coriell panel</TAG>\n"
          + "            <VALUE>MGP00017</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>Population Description</TAG>\n"
          + "            <VALUE>Han Chinese in Beijing, China</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>sex</TAG>\n"
          + "            <VALUE>male</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>HapMap sample ID</TAG>\n"
          + "            <VALUE>NA18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>culture_collection</TAG>\n"
          + "            <VALUE>Coriell:GM18561</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "         <SAMPLE_ATTRIBUTE>\n"
          + "            <TAG>BioSampleModel</TAG>\n"
          + "            <VALUE>HapMap</VALUE>\n"
          + "         </SAMPLE_ATTRIBUTE>\n"
          + "      </SAMPLE_ATTRIBUTES>\n"
          + "   </SAMPLE>\n"
          + "</SAMPLE_SET>";

  public static String expectedFullSampleXml =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE center_name=\"1000G\" alias=\"NA18561\" accession=\"SRS000121\" broker_name=\"NCBI\" center_alias=\"1000G\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>SRS000121</PRIMARY_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"BioSample\">SAMN00001603</EXTERNAL_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"Coriell\">GM18561</EXTERNAL_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"1000G\">NA18561</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>Coriell GM18561</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>9606</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Homo sapiens</SCIENTIFIC_NAME> \n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>Human HapMap individual Coriell catalog ID NA18561</DESCRIPTION>  \n"
          + "    <SAMPLE_LINKS></SAMPLE_LINKS>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>DNA-ID</TAG>  \n"
          + "        <VALUE>NA18561</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Super Population Code</TAG>  \n"
          + "        <VALUE>EAS</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>population</TAG>  \n"
          + "        <VALUE>CHB</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Super Population Description</TAG>  \n"
          + "        <VALUE>East Asian</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Coriell plate</TAG>  \n"
          + "        <VALUE>HAPMAPPT02</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Coriell panel</TAG>  \n"
          + "        <VALUE>MGP00017</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Population Description</TAG>  \n"
          + "        <VALUE>Han Chinese in Beijing, China</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>sex</TAG>  \n"
          + "        <VALUE>male</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>HapMap sample ID</TAG>  \n"
          + "        <VALUE>NA18561</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>culture_collection</TAG>  \n"
          + "        <VALUE>Coriell:GM18561</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>BioSampleModel</TAG>  \n"
          + "        <VALUE>HapMap</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE>\n"
          + "        <TAG>ENA-FIRST-PUBLIC</TAG>\n"
          + "        <VALUE>2010-02-26</VALUE>\n"
          + "      </SAMPLE_ATTRIBUTE>\n"
          + "      <SAMPLE_ATTRIBUTE>\n"
          + "        <TAG>ENA-LAST-UPDATE</TAG>\n"
          + "        <VALUE>2015-06-23</VALUE>\n"
          + "      </SAMPLE_ATTRIBUTE>\n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String exampleSampleThatHasBeenTaxonFixedSAMN02356578 =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE center_name=\"Broad Institute\" alias=\"Acinetobacter lwoffii CIP64.10\" accession=\"SRS485026\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>SRS485026</PRIMARY_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"BioSample\">SAMN02356578</EXTERNAL_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"Broad Institute\" label=\"Sample name\">Acinetobacter lwoffii CIP64.10</EXTERNAL_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>General Sample for Acinetobacter lwoffii NIPH 512</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>981327</TAXON_ID>  \n"
          + "      <SCIENTIFIC_NAME>Acinetobacter lwoffii NCTC 5866 = CIP 64.10 = NIPH 512</SCIENTIFIC_NAME>  \n"
          + "      <COMMON_NAME/>\n"
          + "    </SAMPLE_NAME>  \n"
          + "    <SAMPLE_LINKS> \n"
          + "      <SAMPLE_LINK> \n"
          + "        <XREF_LINK> \n"
          + "          <DB>bioproject</DB>  \n"
          + "          <ID>219244</ID> \n"
          + "        </XREF_LINK> \n"
          + "      </SAMPLE_LINK> \n"
          + "    </SAMPLE_LINKS>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>collection_date</TAG>  \n"
          + "        <VALUE>2011</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>geo_loc_name</TAG>  \n"
          + "        <VALUE>Unknown</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>specific_host</TAG>  \n"
          + "        <VALUE>Homo sapiens</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>isolation_source</TAG>  \n"
          + "        <VALUE>Unknown</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE>  \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>strain</TAG>  \n"
          + "        <VALUE>NIPH 512</VALUE> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";

  public static String exampleSampleThatHasBeenTaxonFixed =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          + "\n"
          + "<SAMPLE_SET> \n"
          + "  <SAMPLE alias=\"BCM-DGRP301\" center_name=\"BCM\" accession=\"SRS003443\"> \n"
          + "    <IDENTIFIERS> \n"
          + "      <PRIMARY_ID>SRS003443</PRIMARY_ID>  \n"
          + "      <EXTERNAL_ID namespace=\"BioSample\">SAMN00014227</EXTERNAL_ID>  \n"
          + "      <SUBMITTER_ID namespace=\"BCM\">BCM-DGRP301</SUBMITTER_ID> \n"
          + "    </IDENTIFIERS>  \n"
          + "    <TITLE>Drosophila melanogaster DGRP-301</TITLE>  \n"
          + "    <SAMPLE_NAME> \n"
          + "      <TAXON_ID>7227</TAXON_ID>  \n"
          + "      <COMMON_NAME></COMMON_NAME>  \n"
          + "      <SCIENTIFIC_NAME xmlns=\"Drosophila melanogaster\"/>\n"
          + "    </SAMPLE_NAME>  \n"
          + "    <DESCRIPTION>Drosophila melanogaster DGRP-301</DESCRIPTION>  \n"
          + "    <SAMPLE_LINKS> \n"
          + "      <SAMPLE_LINK> \n"
          + "        <URL_LINK> \n"
          + "          <LABEL>Drosophila Genetic Reference Panel at Baylor College of Medicine</LABEL>  \n"
          + "          <URL>https://www.hgsc.bcm.edu/content/drosophila-genetic-reference-panel</URL> \n"
          + "        </URL_LINK> \n"
          + "      </SAMPLE_LINK>  \n"
          + "      <SAMPLE_LINK> \n"
          + "        <URL_LINK> \n"
          + "          <LABEL>SAMN00014227</LABEL>  \n"
          + "          <URL>https://www.hgsc.bcm.edu/content/drosophila-genetic-reference-panel</URL> \n"
          + "        </URL_LINK> \n"
          + "      </SAMPLE_LINK> \n"
          + "    </SAMPLE_LINKS>  \n"
          + "    <SAMPLE_ATTRIBUTES> \n"
          + "      <SAMPLE_ATTRIBUTE> \n"
          + "        <TAG>Strain</TAG>  \n"
          + "        <VALUE>DGRP-301</VALUE>  \n"
          + "        <UNITS/> \n"
          + "      </SAMPLE_ATTRIBUTE> \n"
          + "    </SAMPLE_ATTRIBUTES> \n"
          + "  </SAMPLE> \n"
          + "</SAMPLE_SET>\n";
}
