== Frequently Asked Questions (FAQ)
If you cannot find the answer to your question in this FAQ or the BioSamples Database help pages then please email us at biosamples@ebi.ac.uk.

=== How frequent are updates to BioSamples?
BioSamples content is updated daily. Information directly submitted or updated in a source should be reflected within 48 hours. However, occasionally daily updates may be missed due to unexpected circumstances.

=== What pattern do BioSamples accessions follow?
BioSample accessions always begin with `SAM`. The next letter is either `E` or `N` or `D` depending if the sample information was originally submitted to EBI or NCBI or DDBJ respectively. After that, there may be an `A` or a `G` to denote an Assay sample or a Group of samples. Finally there is a numeric component that may or may not be zero-padded.

=== How can I stay informed about BioSamples?
Subscribe to our low-traffic https://listserver.ebi.ac.uk/mailman/listinfo/biosamples-announce[announcement mailing list^].

=== Why do some of my search results not contain my query?
We use ontologies to help refine search queries. This means that your query might match to data a synonym or more specific term than you were looking for; e.g. a search for 'human' will match 'homo sapiens'. Usually a direct match will be ranked higher in the results however.

=== I think some of the data is wrong. Can you fix it?
Most of the data in BioSamples has been submitted by third parties, often via one or more other services. This means that we are unable to go back to submitters for corrections or clarifications. Therefore we do not have the same degree of up front quality control as services with specific curators and submission requirements. We do however try to extract the highest quality of information from the data we are give, for example by mapping to ontologies and using ontology expansion for queries.