= [.ebi-color]#Frequently Asked Questions (FAQ)#
:last-update-label!:
:toc: auto

If you cannot find the answer to your question in this FAQ or the link:../docs[help pages] then please email us at biosamples@ebi.ac.uk.

== How to cite BioSamples? ==
Please use Mélanie Courtot, Luca Cherubin, Adam Faulconbridge, Daniel Vaughan, Matthew Green, David Richardson, Peter Harrison, Patricia L Whetzel, Helen Parkinson, Tony Burdett; BioSamples database: an updated sample metadata hub, Nucleic Acids Research, Volume 47, Issue D1, 8 January 2019, Pages D1172–D1178, https://doi.org/10.1093/nar/gky1061[https://doi.org/10.1093/nar/gky1061]


== How frequent are updates to BioSamples' data?
BioSamples content is updated daily. Information directly submitted or updated in a source should be reflected within 48 hours. However, occasionally daily updates may be missed due to unexpected circumstances.

== What pattern do BioSamples accessions follow?
BioSample accessions always begin with `SAM`. The next letter is either `E` or `N` or `D` depending if the sample information was originally submitted to EBI or NCBI or DDBJ respectively. After that, there may be an `A` or a `G` to denote an Assay sample or a Group of samples. Finally there is a numeric component that may or may not be zero-padded.

== Why are some BioSamples linked to RRIDs?

The Resource Identification, RRID, Initiative began working with the BioSamples databases in the EU and US in order to identify the pancreatic islets used by researchers who are part of the Integrated Islet Distribution Program, IIDP.
Recently the leadership of the IIDP, BioSamples and the RRID project came together to add BioSamples in a limited capacity to the RRID project, which will identify the IIDP samples as RRIDs. More information can be found in the https://scicrunch.org/page/blog/1132[blog post] and the https://scicrunch.org/resources/about/faqs[RRID FAQs].

== What is the Bioschemas export?
Bioschemas is an extension of schemas.org, a markup language for website and services to provide consistently structured information. It adds semantic markup to web pages by describing ‘types’ of information, which then have ‘properties’. The BIoSamples team at EMBL-EBi leads the Bioschemas samples specification work and has added BIoschemas export, serialised as JSON-LD, to all our samples pages. Check out an example https://www.ebi.ac.uk/biosamples/samples/SAMEA104130.ldjson[here].

BioSamples also provides serialisations for other Bioschemas entities embedded in a script tag within the HTML source code, check out examples of the https://www.ebi.ac.uk/biosamples[DataCatalog entity] as well as the https://www.ebi.ac.uk/biosamples/samples[DataSet entity].

== How can I stay informed about BioSamples?
Subscribe to our low-traffic https://listserver.ebi.ac.uk/mailman/listinfo/biosamples-announce[announcement mailing list^].

== Why do some of my search results not contain my query?
We use ontologies to help refine search queries. This means that your query might match to a synonym or more specific term than you were looking for; e.g. a search for 'human' will match 'homo sapiens'. However, direct matches will be ranked higher in the results.

== How will my personal data be used?

This website requires cookies, and the limited processing of your personal data in order to function. By using the site you are agreeing to this as outlined in our https://www.ebi.ac.uk/data-protection/privacy-notice/embl-ebi-public-website[Privacy Notice] and https://www.ebi.ac.uk/about/terms-of-use[Terms of Use].

If you submit information to BioSamples please note that we will handle your submission in accordance with our https://www.ebi.ac.uk/data-protection/privacy-notice/biosamples-submissions[Submission Privacy Notice].

== I think some of the data is wrong. Can you fix it?
Most of the data in BioSamples has been submitted by third parties, often via one or more other services. This means that we are unable to go back to submitters for corrections or clarifications. Therefore we do not have the same degree of up front quality control as services with specific curators and submission requirements. We do however try to extract the highest quality of information from the data we are given, for example by mapping to ontologies and using ontology expansion for queries.

== Where is the BioSamples source code?
BioSamples is an open source database. The source code is published https://github.com/EBIBioSamples/biosamples-v4[here]. Licensing information for the source code is on our https://raw.githubusercontent.com/EBIBioSamples/biosamples-v4/dev/LICENSE[licensing page]. For problems in building your local BioSamples database, please send a pull request or contact us at biosamples@ebi.ac.uk.

== How do I send my SampleTab files to BioSamples?
SamplesTab services have been deprecated and retired on July 1st 2020. Please use our https://www.ebi.ac.uk/biosamples/docs/references/api/submit[JSON API] for sample submission and update.

== My sample doesn’t have a ``Submitted on`` date?
The ``Submitted on`` date field was added in our release in November 2020. All samples submitted after November 17th 2020 will present this information. Older samples may not have that date - this will be progressively added as our curation pipelines periodically run, or can be added on request at biosamples <at> ebi.ac.uk.

== Why was the "ID created on" field removed?
Many users reported confusion interpreting the ``ID created on`` field. To address this issue, we have removed the field from the UI. It has been retained in the JSON source as ``create`` for advanced users familiar with the BioSamples processing pipelines and documentation. ``create`` reflects the date at which the sample accession is created. This attribute is generated by BioSamples. IDs can be created well in advance of collection or submission; BioSamples allows the pre-registration of sample accession to support cross-archive data exchange and data provenance management. IDs can be created by internal pipelines as unallocated placeholders pending user submission, sometimes months in advance of the actual sample collection.
