= [.ebi-color]#Sample dates and timestamps explained#
:last-update-label!:
:toc:

BioSamples keep records of different dates and timestamps related to the sample. The dates can be generated either by data archives or by the data submitters for data exchange or experiment purposes.

BioSamples uses the Coordinated Universal Time (UTC) for all timestamps by default.

== Different dates and timestamps
==== `Released on`

The time that the sample is released. This attribute is provided by data submitters.

Samples are only publicly accessible after the `Released on` time. For public sample metadata which doesn't have data access restrictions, the `released on` date should be the time when the sample is submitted. For samples to be released in the future, please specify the released time.

==== `Update on`

The time that the sample was last updated. This attribute is generated by BioSamples.

The sample can be updated for curation needs and other technical purposes. And the `update on` date shows the date of the latest update. To find details of each curation-related update,  please check the https://www.ebi.ac.uk/biosamples/docs/guides/curation[curation documenation].

==== `Created on`

The time that the sample accession is created. This attribute is generated by BioSamples.

**Note: The `created on` date shows the sample accession creation date, rather than the sample creation date.**

The sample accession date can be created **before** the actual sample collection time.  BioSamples allows the pre-registration of sample accession to support cross-archive data exchange and data provenance management. The sample data can be later added. Pre-registration doesn’t give priority to the process of the sample data.

==== Other dates and timestamps in BioSamples

You might find other timestamps, such as `INSDC first public`, `INSDC last update` in the sample `attributes` section. Such dates are generated by other data archives and indicate the time when BioSamples exchange data with other International Nucleotide Sequence Database Collaboration(INSDC) data archives.

Other sample related times in the sample attributes, for example `collection date`, are provided by the data submitters and shows the actual date when the sample is created.


== Common questions
=== Why is the sample creation date different from the release date?
Some sample accessions are generated before sample submission for data archive exchange or experiment purpose. It's possible that the creation date is earlier than the sample collection date.

=== What was changed in the update date?
To change what has been updated in the latest update, please check the https://www.ebi.ac.uk/biosamples/docs/guides/curation[curation documenation].
