= [.ebi-color]#Sample dates#
:last-update-label!:
:toc:

BioSamples keeps records of different dates related to the sample lifecycle. The dates can be generated either by data archives or by the data submitters for data exchange or experiment purposes.

== Different dates

=== Submitted on

The earliest date at which valid metadata has been provided by the submitter. This attribute is generated by BioSamples and other INSDC partners.

=== Released on

The user-supplied date at which the sample metadata is made available publicly for the first time.

=== Last reviewed

The date at which a new curation object has been created or the automatic curation pipelines have been run on a sample metadata.
This field is only present if at least one curation object has been added by the curation pipelines. The last reviewed date is updated when the curation objects are reviewed,
even if they are found still valid and are not modified and indicates that the sample is compliant with the latest BioSamples curation rules [https://www.ebi.ac.uk/biosamples/docs/guides/curation].
This attribute is generated by BioSamples.

== Other dates in BioSamples

=== INSDC first public` and `INSDC last update

You might find other dates or timestamps in the sample `attributes` section, such as `INSDC first public`, `INSDC last update` in the sample `attributes` section. Such dates are generated by other data archives and reflected after data exchange with other International Nucleotide Sequence Database Collaboration (INSDC) data archives.

