= [.ebi-color]#Search#
:last-update-label!:
:toc:

== How to search BioSamples
In the top right corner of every page (including this one!) you can find a search box.
You can enter any words that you want describe your samples of interest here. Once a query has been entered, press return or click on adjacent button to view the results.

The main section of the results page is stack of samples that match your search term. Each of them is described in summary, and can be clicked on to go to a dedicated page with more details. The results are ordered by quality of match.

On the left of the side are a collection of facets that you can use to refine your query. Picking one or more of these will limit the results displayed to only those that have that specific attribute type and value. Once a facet has been selected, it is remove from the list; to de-select a facet, simply click on the cross displayed next to the badge at the top of the page.

If there are many results for a query then they will be split over multiple pages; to change page, use the controls underneath the facets on the left.

== Advanced search
As as as simply entering the terms you wish to search for, there are some additional features of the search that might be useful to find samples of interest.

=== Double quotes
Sometimes you will want to search for a specific phrase and this can be controlled by surrounding the phrase within double quotes e.g. to search for breast cancer you can use: `"breast cancer"` . This will make sure that your results match your query entirely as adjacent words in the result, rather than matching just part of it or matching it at different parts of the result.

=== Boolean queries

Each word in the query is treated as a separate term (unless surrounded by double quotes) and by default a result only has to contain one of the terms.

This behaviour can be modified by using boolean operators (`AND` `OR` `NOT`) and round brackets e.g. to find mouse or human samples that do not have leukmemia you can use: `NOT Leukemia AND ( mouse OR human )` .

=== Wildcards
Queries containing star or question mark characters are treated separately. A star character will match any combination of zero or more characters e.g. `leuk*mia` will match to 'leukemia' and 'leukaemia' as well as 'leukqwertymia'. A question mark character will match any single characters e.g. `m?n` will match both man and men.

NOTE: for technical reasons, wildcards cannot be at the beginning of words e.g. `?ouse` .

=== Range queries
Certain attributes can be queried for ranges of matching values. For example for things that were last updated between the 1st and 4th of April 2014.

Attributes that can be searched using ranges are:

* Last update date e.g. `updatedate:[2014-04-01 TO 2014-04-04]`
* Release date e.g. `releasedate:[2014-04-01 TO 2014-04-04]`

NOTE: the date syntax is `yyyy-MM-dd` with a double digit month and day required.

=== Filters
