= [.ebi-color]#Sample dates#
:last-update-label!:
:toc:

BioSamples keeps records of different dates related to the sample lifecycle. The dates can be generated either by data archives or by the data submitters for data exchange or experiment purposes.

== Different dates

=== Submitted on

The earliest date at which valid metadata has been provided by the submitter. This attribute is generated by BioSamples and other INSDC partners.

=== Released on

The user-supplied date at which the sample metadata is made available publicly for the first time.

=== Last updated by submitter

The last date at which the sample metadata was updated by the submitter. Submitter updates differ from curation as the original record is modified to include the changes.

=== Last updated by curation

Curation of samples is done periodically, and includes curation by automated pipelines or manually by users. Curation differs from submitter updates as the original record is not modified; changes are added as an overlay.
More information about curation is available in the documentation [https://www.ebi.ac.uk/biosamples/docs/guides/curation]. This attribute is generated by BioSamples.

=== Collected on

The original collection date of the sample. This date is only available if the user has provided a collection date a part of the sample metadata. Collection date can be provided with attribute name as collection date or collection_date (case insensitive).

== Other dates in BioSamples

=== INSDC first public` and `INSDC last update

You might find other dates or timestamps in the sample `attributes` section, such as `INSDC first public`, `INSDC last update` in the sample `attributes` section. Such dates are generated by other data archives and reflected after data exchange with other International Nucleotide Sequence Database Collaboration (INSDC) data archives.

