= [.ebi-color]#Sample dates and timestamps explained#
:last-update-label!:
:toc:

The BioSamples database keeps records of different dates and timestamps related to the sample. The dates can be generated either by data archives or by the data submitters for data exchange or experiment purpose.

BioSamples uses the Coordinated Universal Time (UTC) for all timestamps and dates by default.

== Different dates and timestamps

==== `ID Created on`

The time that the sample accession is created. This attribute is generated by BioSamples.

**Note: The `ID created on` date shows the sample accession creation date, rather than the creation date of the sample data.**

The sample accession date can be created **before** the actual sample collection time.  BioSamples allows the pre-registration of sample accessions to support cross-archive data exchange and data provenance management. The sample data can be later added. Pre-registration doesn’t give priority to the process of the sample data.

==== `Submitted on`
The earliest date at which valid metadata has been provided by the submitter. This attribute is generated by BioSamples and other INSDC partners.

==== `Released on`

The time that the sample is released. This attribute is provided by data submitters.

Samples are only publicly accessible after the `Released on` time. For public sample metadata which doesn't have data access restrictions, the `released on` date should be the time when the sample is submitted. For samples to be released in the future, please specify the released time.

==== `Updated on`

The time that the sample is last updated. This attribute is generated by BioSamples.

The sample can be updated for curation needs and other technical purposes. And the `update on` date shows the date of the latest update. To find details of each curation-related update,  please check the https://www.ebi.ac.uk/biosamples/docs/guides/curation[curation documenation].

=== Other dates and timestamps in BioSamples

==== `Collection date`
Other dates can be included in the sample `attributes` section, for example “collection date” is the user-supplied date at which the sample was collected.

==== `INSDC first public`
You might find other dates or timestamps in the sample `attributes` section, such as `INSDC first public`, `INSDC last update` in the sample `attributes` section. Such dates are generated by other data archives and reflected after data exchange with other International Nucleotide Sequence Database Collaboration (INSDC) data archives.


== Common questions

=== What was changed on the update date?

To check what has been updated in the latest update, please check the https://www.ebi.ac.uk/biosamples/docs/guides/curation[curation documenation].

=== Why is the sample “ID created on” date different from the “Submitted on” date?
Sample accessions may be generated well in advance of sample metadata submission, for example when samples are pre-registered. The creation date indicates the date at which an ID was created in the database.

=== My sample doesn’t have a "Submitted on" date?
The Submitted on date field was added in our release in November 2020. All samples submitted after November 17th 2020 will present this information. Older samples may not have that date - this will be progressively added as our curation pipelines periodically run, or can be added on request at biosamples <at> ebi.ac.uk.