= [.ebi-color]#Search#
:last-update-label!:
:toc:
:linkattrs:

== How to search BioSamples
In the top right corner of every page (including this one) you will find a search box.
Enter keywords that describe the samples that you would like to find. Once your query has been entered, press return or click on the adjacent button to view the results.

Your search results will be displayed as a stack of sample records that match your search terms, ordered by the most relevant results first. In each record you will see a summary of the associated metadata but you can click on each sample to go to a dedicated page with further details.

On the left side of the page you will see the available metadata attributes as facets that you can further use to refine your query. Picking one or more of these facets will limit the results displayed to those that match the newly specific criteria after you click on the button to apply the filters. Selecting the facet title will filter samples that contain the attribute, whilst selecting a facet value will more precisely filter samples that contain the attribute type/value pair. You can select combinations of both the facet title and one or more of the facet values. You can read more about this in the dedicated <<filters,filters section>>

If there are more than 10 results for a query then they will be split over multiple pages; to change page, use the controls underneath the facets on the left.

== Advanced search
As simply entering the terms you wish to search for, there are some additional features of the search that might be useful to find samples of interest.

=== Double quotes
Sometimes you will want to search for a specific phrase and this can be controlled by surrounding the phrase within double quotes e.g. to search for breast cancer you can use: `"breast cancer"` . This will make sure that your results match your query entirely as adjacent words in the result, rather than matching just part of it or matching it at different parts of the result.

=== Boolean queries

Each word in the query is treated as a separate term (unless surrounded by double quotes) and by default a result only has to contain one of the terms.

This behaviour can be modified by using boolean operators (`AND` `OR` `NOT`) and round brackets e.g. to find mouse or human samples that do not have leukmemia you can use: `NOT Leukemia AND ( mouse OR human )` .

=== Wildcards
Queries containing star or question mark characters are treated separately. A star character will match any combination of zero or more characters e.g. `leuk*mia` will match to 'leukemia' and 'leukaemia' as well as 'leukqwertymia'. A question mark character will match any single characters e.g. `m?n` will match both man and men.

NOTE: for technical reasons, wildcards cannot be at the beginning of words e.g. `?ouse` .

=== Range queries
Certain attributes can be queried for ranges of matching values. For example for things that were last updated between the 1st and 4th of April 2014.

Attributes that can be searched using ranges are:

* Last update date e.g. `updatedate:[2014-04-01 TO 2014-04-04]`
* Release date e.g. `releasedate:[2014-04-01 TO 2014-04-04]`

NOTE: the date syntax is `yyyy-MM-dd` with a double digit month and day required.

[#primitives-nulls]

[#filters]
=== Filters

The search interface provide a quick and easy way to filter the results based on attributes type and value. This is done
using the facets available on the left side of the screen.

Each facet represents an attribute with 10 of the most common values for that attributes. Clicking on the facet title
will filter the results of your query to samples having the attribute with any value, while clicking on one of the facet sublist will filter the results to only show samples having that specific attribute type-value pair.

You can compose filter using different attributes or even different values from the same attribute.
Selecting different facets will produce an intersection of the results, like an AND operator between the filters, while selecting different values within the same facet will generate an union of the results, like an OR operation between the two filters.

*NOTE*: To apply the filters you need to click the *Apply filters* button at the top of the facet list

You can also try to create manual filter following the link:../references/filters[reference guide on filters, window='_blank']

== Some search use cases
In this section we will show some example of queries which could be of potential interest for the user

=== Filter samples by project
Many samples uses the `project` attribute do describe which project they are part of. Some examples are the FAANG project, as well as HipSci or EBiSC.
You can get a feeling of the projects using a filter on the project attribute. Note that if the facet for the project attribute is not available in the facet list, you can still hardcode th
e filter in the URL as explained in the link:../references/filters[reference guide on filters, window='_blank']

To show only the samples with a project attribute select the project facet from the facet list (if available), or add `filter=attr:project` to the url after the `search?`.
You can see the result of such filter using link:/biosamples/samples?filter=attr:project[this link, window='_blank'].

You should be able to see now the project facet on the left side of the page. You can select one or more values from it to further filter the results based on specific project[s]. Check out link:/biosamples/samples?filter=attr:project:FAANG&filter=attr:project:HipSci[this link, window='_blank'] to see a search for FAANG and HipSci samples.

[#filter_by_external_archive]
=== Filter samples with data in an external archive
Many samples in BioSamples have external data associated to them and stored in other archives, like ENA or ArrayExpress.
If you want to filter your query to samples with data in a specific archive, you can do that using an link:../references/filters#_external_reference_data[External Reference Data filter, window='_blank'].

To see what are the most used external archives with data associated to sample, select the `external reference` facet from the list of facets available on the left side of the screen, or add `filter=attr:external+reference` to the url after the `search?` bit.

Check out the result page for this query link:/biosamples/samples?filter=attr:external+reference[here, window='_blank']

A list of available external archives will be available in the facet list. Click the archive you're interested in, e.g. ArrayExpress, or add the corresponding value to the url, i.e. `filter=attr:external+reference:ArrayExpress`.

Check out the result page for this query link:/biosamples/samples?filter=attr:external+reference:ArrayExpress[here, window='_blank']

=== Get sample metadata associated to an ENA accession
There are cases where you have an ENA accession available but you need to retrieve the sample metadata associated to such accession from BioSamples.

The best way to get the sample, or samples, associated to an ENA accession is to use an external reference data filter. You can read the details about this in the link:../references/filters#_external_reference_data[filters reference page, window='_blank']

Even if using facet is the easiest way of creating filters in the UI, the specificity of the request make it easier to manually add the filter to the url.
If for example you want to get all the samples associated to the ENA accession SRS359918, just add  `filter=extd:ENA:SRS359918` after the `search?` part of the url.

Check out the result of this filter at link:/biosamples/samples?filter=extd:ENA:SRS359918[this page, window='_blank']

You can follow the procedure explained in the "<<filter_by_external_archive>>" section to check what are the most used archives in BioSamples






