= [.ebi-color]#Sample dates#
:last-update-label!:
:toc:

BioSamples keeps records of different dates related to the sample lifecycle. The dates can be generated either by data archives or by the data submitters for data exchange or experiment purposes. 

== Different dates 

=== `ID Created on`

The date at which the sample accession is created. This attribute is generated by BioSamples. IDs can be created in advance of collection or submission; BioSamples allows the pre-registration of sample accession to support cross-archive data exchange and data provenance management

=== `Submitted on`

The earliest date at which valid metadata has been provided by the submitter. This attribute is generated by BioSamples and other INSDC partners.

=== `Released on`

The user-supplied date at which the sample metadata is made available publicly for the first time.

=== `Updated on`

The last date at which the sample was updated. Samples can be updated for curation needs and other technical purposes. More information about curation is available in the documentation [https://www.ebi.ac.uk/biosamples/docs/guides/curation] This attribute is generated by BioSamples.

== Other dates in BioSamples

=== `Collection date`

Other dates can be included in the sample `attributes` section, for example “collection date” is the user-supplied date at which the sample was collected.

=== `INSDC first public`

You might find other dates or timestamps in the sample `attributes` section, such as `INSDC first public`, `INSDC last update` in the sample `attributes` section. Such dates are generated by other data archives and reflected after data exchange with other International Nucleotide Sequence Database Collaboration (INSDC) data archives.

