:last-update-label!:
== Legacy XML programmatic interface

BioSamples Database provides an interface that is suitable for programmatic queries. This consists of four entry point URLs ( descibed below), each of which returns an XML response.

If you have any problems or suggestions please mailto:biosamples@ebi.ac.uk[contact us].

=== Sample Accession

- Returns information about a single specified sample.
- `/biosamples/xml/samples/ACCESSION` where `ACCESSION` is the BioSample Database accession of the sample of interest.
- e.g. +++<a th:href="@{/xml/samples/SAME315173}" th:text="@{/xml/samples/SAME315173}">/xml/samples/SAME315173</a>+++
- +++<a th:href="@{/help/legacy_xml_api_sample_accession}">more information</a>+++

=== Group Accession

- Returns information about a specified group.
- `/biosamples/xml/groups/ACCESSION` where `ACCESSION` is the BioSample Database accession of the group of interest.
- e.g. +++<a th:href="@{/xml/groups/SAMEG82620}" th:text="@{/xml/groups/SAMEG82620}">/biosamples/xml/groups/SAMEG82620</a>+++
- +++<a th:href="@{/help/legacy_xml_api_group_accession}">more information</a>+++

=== Find Samples

- Returns sample accessions that match the specified search query.
- `/biosamples/xml/samples?query=QUERY` where `QUERY` is the term to query for.
- e.g. +++<a th:href="@{/xml/samples(query='leukemia')}" th:text="@{/xml/samples(query='leukemia')}">/biosamples/xml/samples?query=leukemia</a>
- Results are returned in one or more pages and will always return result summary information.
- Can use link:/biosamples/help/search[advanced query features].
- If query is blank, all samples within that group are matched.
- +++<a th:href="@{/help/legacy_xml_api_find_samples}">more information</a>+++

=== Find Groups

- Returns group accessions that match the specified search query.
- `/biosamples/xml/groups?query=QUERY` where `QUERY` is the term to query for
- e.g. +++<a th:href="@{/xml/groups(query='leukemia')}" th:text="@{/xml/groups(query='leukemia')}">/biosamples/xml/groups?query=leukemia</a>+++
- Results are returned in one or more pages and will always return result summary information.
- Can use +++<a th:href="@{/help/search}">advanced query features</a>+++.
- +++<a th:href="@{/help/legacy_xml_api_find_groups}">more information</a>+++

=== Find Samples Within a Group

- Returns sample accessions that match the specified search query and are in the specified group.
- `/biosamples/xml/groupsamples/ACCESSION?query=QUERY` where `ACCESSION` is the group to query within and `QUERY` is the term to query for.
- e.g. +++<a th:href="@{/xml/groupsamples/SAMEG82620(query='leukemia')}" th:text="@{/xml/groupsamples/SAMEG82620(query='leukemia')}">/biosamples/xml/groupsamples/SAMEG82620?query=leukemia</a>+++
- Results are returned in one or more pages and will always return result summary information.
- Can use +++<a th:href="@{/help/search}">advanced query features</a>+++.
- If query is blank, all samples within that group are matched.
- +++<a th:href="@{/help/legacy_xml_api_find_samples_inside_groups}">more information</a>+++

