= [.ebi-color]#BioSamples documentation#
:last-update-label!:

*Welcome to BioSamples*! A sample repository where you can search, submit and curate sample metadata used in various
projects and context. This documentation should help you better understanding what is BioSamples and how to use our service.

If you are completely new to BioSamples and want to get an overview on how to interact with it, you should start with
the link:getting-started.html[Getting started] page

For more detailed information on specific functionality of BioSamples, checkout our link:guides[guides].

If you're a developer and you need a refresh on how our API works, have a look at our link:api[developer guides]

If you have a question about BioSamples, get a look at the link:faq[FAQ section], or contact us using one of the available channels listed in the link:contacts[contacts page]
 
This website requires cookies, and the limited processing of your personal data in order to function. By using the site you are agreeing to this as outlined in our https://www.ebi.ac.uk/data-protection/privacy-notice/embl-ebi-public-website[Privacy Notice] and https://www.ebi.ac.uk/about/terms-of-use[Terms of Use].

If you submit information to BioSamples please note that we will handle your submission in accordance with our https://www.ebi.ac.uk/data-protection/privacy-notice/biosamples-submissions[Submission Privacy Notice].
 
 