= [.ebi-color]#API Overview#
:last-update-label!:
:toc: auto

== Accessing the service

=== HTTPS vs HTTP
BioSamples content is served using HTTPS protocol by default. For more details about  check  https://www.ebi.ac.uk/about/technology/2017/09/https-by-default/[Technical Services Cluster blog post]

=== Content negotiation
BioSamples leverages content-negotiation for data access. To get more details about content-negotiation you can check then https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[MDN web docs].

.BioSamples's supported content
[cols=3*,options="header"]
|===
|Type
|Header
|Comments

| HTML | `Accept: text/html` |
| JSON | `Accept: application/hal+json` or `Accept: application/json` | Recommended
| JSON-LD | `Accept: application/ld+json` | Use to serve http://bioschemas.org/[BioSchemas] content
| XML | `Accept: text/xml` or `Accept: application/xml` | Soon deprecated
|===

=== Hypermedia

This API uses hypermedia, and resources include links to other resources in their responses. Responses are in
http://stateless.co/hal_specification.html[HAL] format. Links can be found beneath the `_links` key. API users should
not build links themselves, but should use these links to navigate between resources. Clients should discover resources
and available actions by consuming the `_links`.

Links may be returned in templated form, requiring expansion prior to use. This is primarily true for search resources.
Templated links follow https://tools.ietf.org/html/rfc6570[RFC6570].

Link naming follows a consistent pattern.

* Each resource includes a `self` link. This is the canonical link to the resource, although there may be others
* Individual resources are named with the type name, e.g. `sample`
* Collection resources are named with the plural of the type name in camel case, e.g. `samples`, `curations`, `curationLinks`

For a reference of links available in BioSamples check the corresponding <<ref_api_links.adoc#, Links section>>

== Supported HTTP verbs
This API aims to use appropriate HTTP verbs for each action, although not all the actions are supported by our service.
You can read more about HTTP verbs on https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods[MDN web docs].

.BioSamples's API supported verbs
[cols=2*,options="header"]
|===
|Verb
|Description

|`GET`|Used for retrieving resources
|`POST`|Used for creating resources
|`PUT`|Used to entirely replace resources
|`OPTIONS`|Can be used to determine which verbs can be used for a resource
|`HEAD`|Returns whether a resource is available
|===

== HTTP Status codes
BioSamples uses standard HTTP response codes for request to our service. You can find a complete reference on the
HTTP status codes on https://developer.mozilla.org/en-US/docs/Web/HTTP/Status[MDN web docs]

== Authentication
Authentication and authorization decisions are made based on a https://jwt.io/[JWT] token, provided as a HTTP request
header. This is described in the guide to <<guide_accounts_and_logging_in.adoc#,Accounts and logging in>>.

All examples of accessing the API will use `$TOKEN` as a placeholder for your real token.

//== Errors


