= [.ebi-color]#API submission#
:last-update-label!:
:toc: auto


Using the BioSamples API you can submit new samples to our resource, as well as update or curate samples.

This website requires the limited processing of your personal data in order to function. By using the site you are agreeing to this as outlined in our https://www.ebi.ac.uk/data-protection/privacy-notice/biosamples-submissions[Submission Privacy Notice]

== Submission minimal fields

=== Sample
Sample content reference:
[cols=4*, options="header"]
|===
|Field
|Description
|Type
|Cardinality

| name | The short name of the sample. | `String` | Required
| release | The date at which the sample was first made public. | `Date ISO 8601` | Required
| update | The date at which the sample was last updated. | `Date ISO 8601` | System Generated
| domain | The AAP domain the sample belongs to. | `String` | Required
| accession | The sample unique identifier in the BioSamples database. If not provided, one will be automatically assigned. | `String` | Required for `PUT` requests
| characteristics | The key-value pairs representing the attributes of the sample. | `Object` | Optional
| externalReferences | A list of links towards external references, such as datasets in other archives. | `Array` | Optional
| relationships | A list of relationships this sample has to other, existing, samples. | `Array` | Optional
| data | A more structured data format to allow submission of tables (eg. antibiogram) in addition to key-value pairs.| `Array` | Optional, required only for structured data submission using our POST, PUT or PATCH endpoints.
Note - You must provide an AAP domain for your data. It can be same as the sample domain if you are the submitter of both the
sample metadata and structured data.
|===

=== Curation Link
[cols=3*, options="header"]
|===
|Field
|Type
|Cardinality

| sample | `String` | Required
| domain |  `String` | Required
| curation | `Object` | Required
| curation.attributesPre | `Array` | Required, could be empty
| curation.attributesPost | `Array` | Required, could be empty
| curation.externalReferencesPre | `Array` | Required, could be empty
| curation.externalReferencesPost | `Array` | Required, could be empty
| domain | `String` | Required
|===


== Submit a sample
`POST` sample to BioSamples


=== Request
include::{snippets}/post-sample/http-request.adoc[]

=== Response
include::{snippets}/post-sample/http-response.adoc[]

=== Links
For all the links available in BioSamples check the link:../api/links[Links Reference]

== Update sample
`PUT` a sample to BioSamples

The submitted sample is required to have an accession and the accession should match the one in the url. Updating a sample overwrites its existing content with the new one. If you want to preserve existing attributes, you should first download the sample, build a new version including existing and new attributes, and resubmit the new content.

=== Request
include::{snippets}/put-sample/http-request.adoc[]

=== Response
include::{snippets}/put-sample/http-response.adoc[]

=== Links
For all the links available in BioSamples check the link:../api/links[Links Reference]

== Submit structured data to sample
`PATCH` a sample to BioSamples

This endpoint is useful if an user wants to add structured data to an existing sample
(example: Antibiogram data of sample)

The sample structured data submission is not required to be done at the time of the sample
submission and also by the original submitter. Structured data can be submitted at a later point
of time by another submitter. Ownership rights will be retained and sample submitter can later
update the sample metadata only and structured data submitter can update the structured data only.

Pre Conditions:

1. The submitted sample is required to have an accession and the accession should match the one in the url
2. The submitted sample should also have the sample name and the structured data
3. The structured data must have a structured data type (e.g. AMR) and a valid AAP domain
4. This endpoint doesn't accept any other data except sample name, accession and structured data.
    If you supply any other information, your input will not be accepted

=== Request
include::{snippets}/patch-sample/http-request.adoc[]

=== Response
include::{snippets}/patch-sample/http-response.adoc[]

=== Links
For all the links available in BioSamples check the link:../api/links[Links Reference]


== Submit curation object
`POST` a curation to BioSamples

=== Request
include::{snippets}/post-curation/http-request.adoc[]

=== Response
include::{snippets}/post-curation/http-response.adoc[]

=== Links
For all the links available in BioSamples check the link:../api/links[Links Reference]


== Accession a sample
`POST` a sample for accessioning. Accessioned sample is saved as a private sample.

=== Request
include::{snippets}/accession-sample/http-request.adoc[]

=== Response
include::{snippets}/accession-sample/http-response.adoc[]

=== Links
For all the links available in BioSamples check the link:../api/links[Links Reference]


== Validate sample fields
`POST` a sample to validate its basic fields before submission.

=== Request
include::{snippets}/validate-sample/http-request.adoc[]

=== Response
include::{snippets}/validate-sample/http-response.adoc[]


== Post sample with external references
`POST` sample with external reference attached to it

=== Request
include::{snippets}/post-sample-with-external-references/http-request.adoc[]

=== Response

include::{snippets}/post-sample-with-external-references/http-response.adoc[]

== Put sample with relationships
`PUT` sample with relationships

=== Request
include::{snippets}/put-sample-with-relationships/http-request.adoc[]

=== Response
include::{snippets}/put-sample-with-relationships/http-response.adoc[]

=== Links
For all the links available in BioSamples check the link:../api/links[Links Reference]

