= [.ebi-color]#Release notes#
:toc: auto

This pages contains links to release notes for BioSamples for version 4.0.0 and higher. This release represents a comprehensive overhaul and therefore previous release notes are no longer applicable.

[[section]]
4.1.11
----
* Added support for suppressed samples to enable dbGap data loading
* Fix confusion between supressed and private samples in dbGap data
* Livelist file: adding flush to make sure file is written
* Add validation and accessioning service
* Fix SampleTab template download link

[[section]]
4.1.10
----
* Remove the holiday message
* Fix submit tab link in error pages


[[section]]
4.1.9
----
* Added a Curation Undo Pipeline to allow for removal of erroneous curations.
* Fix an issue where long attributes break the sample box UI.


[[section]]
4.1.8
----
* Corrected error in curation pipeline which caused sample characteristics to be removed erroneously
* Added holiday message


[[section]]
4.1.7
----
* Added libraries to enable applications to use Graylog to allow configuration of aggregated logging
* Switched to the AAP explore environment at https://explore.api.aai.ebi.ac.uk
* Updated the default AAP URL used by the BioSamples client
* Included sampletab template file in the sampletab documentation
* Included ETAG and Curation Object recipes to the BioSamples cookbook
* Removed name and API key lookup functionality from SampleTab process


[[section]]
4.1.6
----

* Addition of AMR structured data into BioSamples
* Submission of samples with a relationship not targeting a valid accession now return an error
* Fixed bug with Phenopacket export not able to extract medatada for Orphanet terms
* Updated user interface to use the newer version of the EBI visual framework
* Improved documentation navigation experience adopting a new menu style


[[section]]
4.1.5
----

* Fixed bug that search failed when using a colon with a non-indexed field. e.g. taxon:9696
* Added the BioSamples cookbook
* Fixed issue where there are duplicate organism attributes with different cases in a sample
* Updated the error message in the SampleTab UI to take into account large submissions timeout


[[section]]
4.1.4
----

* As part of curation pipeline attributes with the value "not_applicable" are removed
* Date titles on the sample page are now "Releases on" and "Updated on" rather than "Release" and "Update"
* An initial accession endpoint has been added to the REST API to enable ENA to get a list of accessions for a project
* A multi-step Docker build has been added to allow Docker images to be distributed on quay.io
* A fix has been made for an issue that caused the Zooma Pipeline to fail on wwwdev


[[section]]
4.1.3
----

* Additional sample attributes required by ENA are now available including a single, top-level taxId field
* The export box for a sample is now renamed download and contains a list of serialisations that always download as a file fixing a blocked popups issue in Safari
* The search results now have an updated look and feel based on feedback from ENA


[[section]]
4.1.2
----

* Sample JSON now contains a numeric taxId field at the top level
* IRI of ontology terms now resolve to the defining ontology when they are available in multiple ontologies
* Requests for a sample now contain a computed ETag header to identify changes
* When requesting a private sample an explanation message is now provided in addition to the 403 error code
* The search UI now contains a clear filters button


[[section]]
4.1.1
----

* Expose the BioSchemas markup with enhanced context and Sample ontology code
* SampleTab submission pipeline has been rewritten for better robustness
* In the samples results page, the sample name and the sample accession are now linking to the single sample page
* Fixed various broken hyperlinks on the home page and in documentation


[[section]]
4.1.0
----

### New features

* GDPR:
** SampleTab submissions enforce explicit acceptance of the terms of service and the privacy information
** GDPR notices added throughout
* SampleTab where targets of relationships are neither sample name nor sample accession are now rejected, providing user additional information on the problematic data
* *Bioschema.org* entities are exported in BioSamples and available both in the UI - embedded in a script tag - and through the API

### Bug fixes
* Solved issues with wrong header’s hyperlinks
* Solved issue with resolving relationship by name in SampleTab submissions
* Solved issue with converting DatabaseURI to external references in SampleTab submissions
* Improved special characters handling in SampleTab submissions


[[section]]
4.0.7
-----

This is a bugfix release that addresses the following issues:

* GDPR notices
* Update format of the Sitemap file

[[section]]
4.0.6
-----

This is a bugfix release that addresses the following issues:

* Improves search handling of special characters in facets
* Improves search handling of special characters in search terms
* Fix issue with curation link URLs
* Implemented DataCatalog, Dataset and DataRecord profiles on JSON+LD
* Add ability to control which curation domains are applied to a sample
* Updated and improved API documentation
* Updated and improved SampleTab documentation
* Fix links to XML and JSON serialisation in the UI
* Fix bug in handling special characters in SampleTab submission
* Add export pipeline
* Add copy down pipeline

[[section]]
4.0.5
-----

This is a bugfix release that addresses the following issues:

* Improved consistency of paged search results if any of the samples are added or modified whilst paging
* Improved search update throughput by using Solr transaction log
* Updated JSON+LD format to the latest version
* Correctly accept XML sample groups and their related samples
* Fix issue related to search query terms not being applied to legacy XML and legacy JSON endpoints.
* Fix incorrect HAL links on autocomplete endpoint
* Replace SampleTab submitted relationships by name with accessions. As a consequence, they can now be consistently cross referenced by accession in user interface and API
* Improved indexing of samples when they are rapidly updated or curated
* Updated Elixir Deposition Database banner URL
* Reduce number of Zooma calls by not attempting to map "unknown" or "other" attributes
* Reduce load on OLS by ensuring Zooma does not requery OLS as any results from OLS would not be used by BioSamples

[[section]]
4.0.4
-----

This is a bugfix release that addresses the following issues:

* Persistence of search terms and filters when using HAL paging links
* SameAs relation in the legacy JSON API works as intended
* Removed residual test endpoints from legacy JSON API
* Details relation in legacy JSON API now correctly resolves
* Added informative and specific title to webpages
* Added https://www.elixir-europe.org/platforms/data/elixir-deposition-databases[Elixir Deposition Database] banner

[[section]]
4.0.3
-----

This is a bugfix release that addresses the following issues:

* Forward legacy group URLs /biosamples/groups/SAMEGxxxx to /biosamples/samples/SAMEGxxxxx
* Missing or malformed update and release date on legacy XML group submission will default to current datetime. It is not recommended that users intentionally rely on this.
* Index legacy XML group submissions, which was not happening due to an unexpected consequence of the interaction of components.
* Redirect /biosamples/sample and /biosamples/group URLs in case of typo

[[section]]
4.0.2
-----

This is a bugfix release that addresses the following issues:

* Fix javascript on SampleTab submission and accession
* Handle load-balanced accessioning
* Fix for storage of relationships source on new samples

[[section]]
4.0.1
-----

This is a bugfix release that addresses the following issues:

* Fix submission of new unaccessioned samples with relationships by inserting an assigned accession into the source of any relationships that are missing it.
* Fix curation pipeline of numeric organism iri to "http://purl.obolibrary.org/obo/NCBITaxon_+taxId" when it should be "http://purl.obolibrary.org/obo/NCBITaxon_"+taxId e.g. http://purl.obolibrary.org/obo/NCBITaxon_9606
* Allow CORS requests for legacy XML APIs.
* Updated homepage project sample links to use a filter search rather than a text search.

[[section]]
4.0.0
-----

Version v4.0.0 represents a re-architecture and re-engineering of the
BioSamples software stack. It is now based on the Java
https://projects.spring.io/spring-boot[Spring-Boot] framework, utilising
https://www.mongodb.com[MongoDB] for storage and
https://lucene.apache.org/solr[Solr] for indexing and search. It tries
to follow up-to-date web standards and conventions, while remaining
backwards compatible. This will also give us a strong and stable
foundation to build more features and improvements from, more reliably
and more rapidly.

Highlights include:

* Submissions and updates will be available immediately via accession,
and will be available via search within a few minutes or less. There is
also improved handling of submissions and updates, with fewer errors and
better feedback about any problems.
* Integration with https://aap.tsi.ebi.ac.uk[EBI AAP] for login
management and access to pre-publication samples, including use of
https://www.elixir-europe.org/services/compute/aai[ELIXIR AAI] single
sign-on accounts.
* Separation of submitted sample information from curation of that
information, including the ability for 3rd party (re-)curation of
samples. Please contact us if you would be interested in more
information and/or to supply curation information.
* Improved handling of non-alphanumeric characters in attribute types
e.g. "geographic location (country and/or sea)"
* Improved faceting allowing selection of multiple values within same
facet, fixed re-use and re-distribution of search URLs. This will be
expanded in future with additional facet types where appropriate.
* Support and recommend the use
of https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[content
negotiation] to accessing multiple formats at the same URIs. In addition
to the content (HTML vs XML vs JSON) this also supports
https://developer.mozilla.org/en-US/docs/Web/HTTP/Compression[compression]
and https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching[caching]
through standard mechanisms.
* Java client using Spring, and a Spring-Boot starter module for easy
use. This is used by BioSamples internally and other teams at EMBL-EBI,
so is high performance and battle tested.
* Containerisation using Docker and Docker-Compose, which makes it
easier to run a local version for client development or for local
storage of sample information.

[[data-content]]
Data content
~~~~~~~~~~~~

* Ontology terms Numeric tax IDs (e.g. 9606) and short ontology terms
(e.g. PATO:0000384) are being replaced with full IRIs (e.g.
http://purl.obolibrary.org/obo/NCBITaxon_9606 and http://purl.obolibrary.org/obo/PATO_0000384 )
in many places, eventually everywhere.
* Groups will continue to exist for backwards compatibility purposes.
However, we are investigating future development to reduce or remove
many of these in favour of alternatives such as filtering samples by
external link, or delegating grouping of samples to other EMBL-EBI
archives such as https://www.ebi.ac.uk/biostudies[BioStudies].

[[jsonbiosamples]]
JSON `/biosamples`
~~~~~~~~~~~~~~~~~~

This is the preferred API for use, and uses the same URIs as the HTML
pages, and utilising content negotiation to provide a JSON response.
This is designed as
a https://en.wikipedia.org/wiki/Hypertext_Application_Language[hypermedia
as the engine of application state (HATEOS) API] and therefore we
recommend users do not use specific URLs but rather follow relationships
between API endpoints, much like a user would use links between HTML
pages. It is similar to the `/biosamples/api` JSON format, with a few
critical differences:

* added __release__ in full ISO 8601 format including time. The
backwards-compatible __releaseDate__ exists but should be considered
deprecated and will be removed in a future release.
* added __update__ in full ISO 8601 format including time.
The backwards-compatible __updateDate__ exists but should be considered
deprecated and will be removed in a future release.
* removed __description__ as a separate field, is now available as
a __characteristic__. 
* remove **relations** rel link; equivalent information is now embedded
in sample in __relationships__ and __externalReferences__ lists.
* remove **sample** rel link; with relations now embedded, this link
serves no purpose.
* added **curationLinks** rel link.
* ordering may be different.
* fields are not displayed if empty or null.
* characteristic names accurately reflect what was submitted and may now
be multiple words and may include non alphanumeric characters (e.g
brackets, greek letters, etc). In the `/biosamples/api` responses
characteristic names were always camelCased and with non-alphanumeric
characters removed.
* external references directly embedded in the samples and the groups.

[[xmlbiosamplesxml]]
XML `/biosamples/xml`
~~~~~~~~~~~~~~~~~~~~~

We are maintaining this for backwards compatibility. Later in 2018 we
will be consulting about future development of this API, particularly in
the context of the improved JSON `/biosamples` API using content
negotiation and several long-standing issues with limitations arising
from the XML schema in use.

* XML element *TermSourceREF* element *Name* and element *URI* are
removed.
* XML element *Property* attributes characteristic and comment always
false.
* elements and attributes may be in different order.
* allows only one IRI on attributes, so in rare cases of multiple IRIs
will not be complete.
* Query parameter `query` has now a default value of * if none is
provided.
* Query parameter `sort` is ignored for the search, due to undefined
behaviour and lack of usage.

[[json-biosamplesapi]]
JSON `/biosamples/api`
~~~~~~~~~~~~~~~~~~~~~~

This API should be considered **deprecated** and we will aim to remove
it by 2019. Any users of this should move to using the `/biosamples`
URIs to retrieve JSON representations with an improved schema via
content negotiation. Further announcements will be made in future for
specific updates and deadlines.

* ordering may be different from previous versions, and is not
guaranteed for future versions.
* fields are not displayed if empty or null.
* `/api/externallinksrelations/{id}/sample` and
`/api/externallinksrelations/{id}/group` are removed due to lack of
usage.
* fixed _externalReferences_ and _publications_ to be nested objects and
not JSON strings.

[[acknowledgements]]
Acknowledgements
~~~~~~~~~~~~~~~~

This release has been made possible with the support of our funders:

* EMBL-EBI Core Funds
* EC -ELIXIR-EXCELERATE
* WT- HIPSCI
* IMI - EBiSC
* ELIXIR – Meta Data Implementation Study
* WT-GA4GH
