== SampleTab SCD section

The Sample Characteristics Description is the section that describes the samples as a series of key : value attributes.

In contrast to the MSI section, the SCD section is column based. The start of the SCD section is denoted by [SCD] on a line by itself. The first row contains column headers that specify attribute keys; subsequent rows contain the values of each attribute. Not all columns have to be filled in for all rows; for samples where a particular attribute or attribute modifier does not apply, then those cells can simply be left blank.

There are several types of column headers:

Object definitions. This is Sample Name.
Named attributes: attributes with a specific name such as Sex or Organism.
Free-form attributes: attributes that have a user-specified name component.
Attribute modifiers. These columns modify the closest attribute to the left by specifying units or ontology terms.
Relationships. These are key : value pairs where the value is a different sample. This includes family relationships and assertions of equivalence and/or derivation.
Screenshot of SCD section
Object Definitions
The SCD section of a SampleTab file contains definitions BioSamples. These are denoted by a column header key of Sample Name and a unique value within that file. The same object can be used in multiple places within the same file, but all attributes identical in all uses.

Object names should be alphanumeric without punctuation. Furthermore, names should be different by more than just capitalization (e.g. the use of both "Subject A" and "Subject a" is discouraged). Names should be descriptive where possible, but also should not be more than about 25 characters long.

=== Attributes

BioSamples are described by attributes, which are a pair of a tag and a value. Values are expected to be generally be in lowercase and use American English spellings; abbreviations should be avoided.

BioSamples cannot have multiple copies of the same attribute, but multiple attributes with the same key but different values are permitted.

BioSamples that do not have a value in a column are not considered to have the attribute that that column is associated with.

==== Named Attributes

There are a number of specific attributes that can be used to describe BioSamples, as well as more free-form attribute. The specific attributes are:

[options="header"]
|=========
|Key|Notes
|Organism|Value should be scientific name and have NCBI Taxonomy as a Term Source REF with associated Term Source ID.
|Material|
|Sex|Prefer "male" or "female" over synonyms. May have other values in some cases e.g. yeast mating types.
|=========

==== Free-form Attributes

As well as named attributes, free-form attributes can be used. There are currently two types - Characteristic[ ] and Comment[ ] - and both allow free-form text in both the attribute key and value. It is expected that both key and value are lowercase American English without abbreviations.

Characteristic attributes are used to represent common attributes that are not sufficiently well-defined or highly used to be named attributes. Although any key can be used, they should be consistently used by multiple submissions from multiple sources. Attributes with keys that are specific to that sample (e.g. experimental parameters) should be stored as comment attributes instead of characteristic attributes. The table below represents some of the most common characteristic attribute keys.

[options="header"]
|=========
|Key|Notes
|Characteristic[strain or line]|	
|Characteristic[age]|Should have a Unit attribute modifier
|Characteristic[organism part]|General location on the organism rather than a particular tissue.
|Characteristic[cell type]|
|Characteristic[disease state]|	
|Characteristic[genotype]|	
|Characteristic[developmental stage]|	
|Characteristic[genetic modification]|May have multiple characteristics if multiple genetic modifications have been made.
|Characteristic[clinical history]|
|=========

Comment attributes should be used for information that is important to record, but is of a type that is specific to those BioSamples. For example, internal identifiers, operative names, batch identifiers, etc.

==== Attribute Modifiers

There are currently two possible attribute modifiers, Term Source and Unit. These are mutually exclusive; an attribute may have zero or one modifiers, but not two. These modifiers can be used on any Name Attribute, Characteristic Attribute, or Comment Attribute.

A Term Source modifier is used to link the value of an attribute to an external reference, such as an ontology or other controlled vocabulary such as a taxonomy. The most common uses are for organisms (species) in NCBI Taxonomy and terms in the Experimental Factor Ontology. It is intended that the value of an attribute with a Term Source modifier should be equal to the label of any associated ontology terms, however this may not be practical in all cases.

A Term Source modifier is composed of two columns immediately to the right of the attribute being modified. These columns are Term Source REF and Term Source ID. The value in the Term Source REF column for a term Source modifier must correspond to a Term Source Name in the MSI section of the same SampleTab document.

A Unit modifier is used to specify the units used for a numeric value. For example to clarify if an age is specified in years, months, or weeks. The unit should follow the same guidelines as keys and values --- lowercase American English without abbreviations composed only of letters and numbers. Additionally, units should always be expressed as a singular rather than a plural i.e. "year" not "years". Compound units should contain plurals however, e.g. "micromoles per liter". Where possible, SI units should be used (e.g. "centimeter" rather than "inch"). Some commonly used units are:

[options="header"]
|=========
|Unit|Notes
|year|	
|month|	
|day|	
|meter|	
|decimal degree|e.g. latitude or longitude
|degree Celsius|	
|micrograms per liter|use instead of "ug/L" or "µg/L"
|milimole|use instead of "mm"
|micromole|use instead of "um or "µm"
|practical salinity unit|use instead of "PSU"
|=========

=== Relationships

Connections between BioSamples are indicated through relationships. These are named attributes where the value is either the name of another sample in the submission, or the accession of a sample in the BioSamples Database. The following relationships are currently recognized:




[options="header"]
|=========

|Relationship Key|Notes

|Same as|The same physical sample has multiple BioSample records e.g. from different source databases.

|Derived from|Where one BioSample was derived from another e.g. blood sample from an individual, genetic modification of a cell line.
|Child of|Indicates parentage. Only applicable to sexual organisms; for bacteria see Derived from.

A Derived from relationship can be specified implicitly by having two samples on the same row. In such cases, the right hand sample is derived from the left hand sample. Splitting and pooling of samples can also be specified by having multiple samples on the same row and have the same sample on different rows.