== What is a BioSample?
The definition of a BioSample is deliberately flexible in order to accommodate a wide range of uses. Typically each BioSample corresponds to a discrete physical object that is composed of live biological material.

In most cases BioSample entities are self-evident; such as a blood sample, cell culture or an individual organism. However, a BioSample can also be an environmental sample (e.g. for meta-genomic analysis), a hybrid between two species, parasite infected cell culture, etc.

=== How are BioSamples described?

A BioSample is described using attributes, external references, and relationships to other samples. 

Some key/value pairs examples:

[options="header"]
|================
|Key      |Value
|Organism |Homo sapiens
|Sex      |female
|Cell Type|fibroblast
|================


== What should be submitted to BioSamples Database?

The BioSamples Database is a suitable repository for pre-registering multi-omic submissions (e.g. http://www.hipsci.org/[http://www.hipsci.org]).

Samples that do not have associated data in other EBI databases may also be suitable for submission.

When submitting to other EBI databases (e.g. ENA or ArrayExpress), please note that these share sample information with BioSamples Database. Therefore sample information may be present in BioSamples Database even if the information was not submitted directly to BioSamples Database.

== How to submit BioSamples Database?
Submissions to BioSamples Database should be in link:st[SampleTab file format]. This is a tab-separated spreadsheet-like text format compatible with popular office tools.

Once you have a SampleTab file, you can use the online validation service to ensure it is correct. This will also apply common corrections and ontology mappings that are used to standardise the data.

You can send the validated and corrected SampleTab file by email to mailto:biosamples@ebi.ac.uk[biosamples@ebi.ac.uk]. We aim to respond to submissions within one working day.

== Web Services
There are several services provided for programmatically sending sample information to the BioSamples Database. These are:

Submission service for submitting SampleTab files. Please note that they will not be immediately visible in the web interface, but the assigned accession will be returned immediately as a SampleTab file after the submission.

Validation service for validating SampleTab files without submitting them.

Accessioning service for assigning accessions to samples and groups. Please note that this does not submit any sample information to the database, but will return the assigned accessions immediately.

If you have any questions about these services or would like more information, please contact us at mailto:biosamples@ebi.ac.uk[biosamples@ebi.ac.uk].