//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.11.04 at 05:25:28 PM GMT
//

package uk.ac.ebi.biosamples.xml.samplegroupexport;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BioSampleGroup" type="{http://www.ebi.ac.uk/biosamples/SampleGroupExport/1.0}bioSampleGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "bioSampleGroup" })
@XmlRootElement(name = "BioSamples")
public class BioSamples {

    @XmlElement(name = "BioSampleGroup")
    protected List<BioSampleGroupType> bioSampleGroup;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger timestamp;

    /**
     * Gets the value of the bioSampleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the bioSampleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getBioSampleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link BioSampleGroupType }
     * 
     * 
     */
    public List<BioSampleGroupType> getBioSampleGroup() {
        if (bioSampleGroup == null) {
            bioSampleGroup = new ArrayList<BioSampleGroupType>();
        }
        return this.bioSampleGroup;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *         possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setTimestamp(BigInteger value) {
        this.timestamp = value;
    }

}
