{{- range $serviceName, $config := .Values.services }}
{{- if and $config.enabled ($config.service.enabled | default true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "biosamples.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "biosamples.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: {{ $config.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $config.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "biosamples.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}