//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 01:15:00 PM BST 
//


package uk.ac.ebi.biosamples.xml.summaryinfo;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.biosamples.summaryinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _From_QNAME = new QName("http://www.ebi.ac.uk/biosamples/SummaryInfo", "From");
    private final static QName _To_QNAME = new QName("http://www.ebi.ac.uk/biosamples/SummaryInfo", "To");
    private final static QName _Total_QNAME = new QName("http://www.ebi.ac.uk/biosamples/SummaryInfo", "Total");
    private final static QName _PageSize_QNAME = new QName("http://www.ebi.ac.uk/biosamples/SummaryInfo", "PageSize");
    private final static QName _PageNumber_QNAME = new QName("http://www.ebi.ac.uk/biosamples/SummaryInfo", "PageNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.biosamples.summaryinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SummaryInfo }
     * 
     */
    public SummaryInfo createSummaryInfo() {
        return new SummaryInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/biosamples/SummaryInfo", name = "From")
    public JAXBElement<BigInteger> createFrom(BigInteger value) {
        return new JAXBElement<BigInteger>(_From_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/biosamples/SummaryInfo", name = "To")
    public JAXBElement<BigInteger> createTo(BigInteger value) {
        return new JAXBElement<BigInteger>(_To_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/biosamples/SummaryInfo", name = "Total")
    public JAXBElement<BigInteger> createTotal(BigInteger value) {
        return new JAXBElement<BigInteger>(_Total_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/biosamples/SummaryInfo", name = "PageSize")
    public JAXBElement<BigInteger> createPageSize(BigInteger value) {
        return new JAXBElement<BigInteger>(_PageSize_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/biosamples/SummaryInfo", name = "PageNumber")
    public JAXBElement<BigInteger> createPageNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_PageNumber_QNAME, BigInteger.class, null, value);
    }

}
